export const FAMILY_OCCASIONS = {
  reunion: {
    slug: "virtual-family-reunion-game-show",
    eyebrow: "A reunion everyone can join",
    title: "Virtual Family Reunion Game Show",
    accent: "Bring every generation into the same room.",
    description: "A live host turns your family reunion into an easy, energetic online game show—with custom stories, friendly competition, and no relative stuck running the event.",
    metaDescription: "Host a live virtual family reunion game show with custom trivia, all-ages games, a professional emcee, and no downloads. From $35 per person.",
    image: "/family-occasion-reunion.png",
    imageAlt: "A family laughing together during an online reunion game show",
    occasion: "reunion",
    entryPoint: "family_reunion_money_page",
    intro: "Ideal for families spread across cities, countries, or time zones. We keep the pace moving while making space for the stories and people that make your family unique.",
    benefits: [
      "A professional host runs the entire experience",
      "Questions can include family history and favorite memories",
      "Kids, parents, grandparents, and cousins can play together",
      "Everyone joins from a normal web browser—no downloads",
    ],
    games: [
      ["Family Feud-style showdown", "Teams guess the family’s most popular answers."],
      ["Generations Battle", "Music, movies, sayings, and moments from different decades."],
      ["Family Story Trivia", "Turn approved memories and traditions into personalized questions."],
    ],
    examples: [
      "Which family recipe disappears first at every gathering?",
      "Who has traveled the farthest to join this reunion?",
      "Which decade produced the family’s favorite songs?",
    ],
    faqs: [
      ["Can older relatives participate?", "Yes. Players use a simple browser link, and we adjust the pace, question style, and instructions for the ages in your group."],
      ["Can relatives join from different countries?", "Yes. We help you choose a practical time and everyone can join from their own computer, tablet, or phone."],
      ["Do we have to provide family stories?", "No. We can run a complete show without private details. Custom stories and photos are optional and only used with your permission."],
      ["How many people can join?", "We support small reunions and large extended families. Tell us the number of players and households, and we will recommend the best format."],
    ],
  },
  birthday: {
    slug: "virtual-birthday-game-show",
    eyebrow: "A birthday show built around your guest of honor",
    title: "Virtual Birthday Game Show",
    accent: "More laughs than another group video call.",
    description: "Celebrate together from anywhere with a live-hosted birthday game show, personalized challenges, music, trivia, and a proper birthday finale.",
    metaDescription: "Plan a live virtual birthday game show with a professional host, custom trivia, music, and games for adults or mixed ages. From $35 per person.",
    image: "/family-occasion-birthday.png",
    imageAlt: "Friends and family celebrating a birthday together online",
    occasion: "birthday",
    entryPoint: "family_birthday_money_page",
    intro: "We handle the timing, teams, scoring, and energy so the birthday person gets to enjoy the party instead of managing it.",
    benefits: [
      "Built for adult birthdays, family birthdays, or mixed ages",
      "Custom questions can celebrate the guest of honor",
      "A live emcee keeps every household involved",
      "No game installation or participant account required",
    ],
    games: [
      ["Birthday Spotlight", "Guests compete in challenges inspired by the guest of honor."],
      ["Name That Tune", "Fast music rounds customized to favorite decades and styles."],
      ["Survey Showdown", "Friendly team competition with funny birthday prompts."],
    ],
    examples: [
      "What phrase does the birthday person say most often?",
      "Which song would get them onto the dance floor immediately?",
      "Who has known the guest of honor the longest?",
    ],
    faqs: [
      ["Is this only for children’s birthdays?", "No. The show is especially effective for adult birthdays and family groups. We adjust the content and energy for your guests."],
      ["Can we surprise the birthday person?", "Yes. A family member or friend can provide the approved details while we keep the custom content private until the event."],
      ["Can guests play from different homes?", "Yes. Every household joins the shared video call and opens the game in a browser."],
      ["Can you include photos?", "Yes. Approved photos can be included in selected custom rounds. We will explain exactly what to send after the date is reserved."],
    ],
  },
  distance: {
    slug: "long-distance-family-game-night",
    eyebrow: "Family time without the travel",
    title: "Long-Distance Family Game Night",
    accent: "Feel together, even when you live far apart.",
    description: "Replace the awkward family video call with a live-hosted game night that gives everyone something fun to do, talk about, and remember.",
    metaDescription: "Bring long-distance family together for a live online game night with an emcee, trivia, bingo, music, and all-ages games. No downloads required.",
    image: "/family-occasion-distance.png",
    imageAlt: "Long-distance family members smiling during a virtual game night",
    occasion: "long-distance",
    entryPoint: "long_distance_family_money_page",
    intro: "Perfect for families who want meaningful time together without asking one relative to prepare questions, explain rules, or keep score.",
    benefits: [
      "Easy for relatives joining from different locations",
      "Games create conversation without putting anyone on the spot",
      "Flexible formats for regular family nights or special occasions",
      "One live host handles instructions, pacing, and scoring",
    ],
    games: [
      ["Virtual Family Bingo", "Simple, social play that works well across generations."],
      ["Music & Memories", "Recognizable songs and conversation-starting moments."],
      ["Lightning Trivia", "Short, lively rounds covering interests your family enjoys."],
    ],
    examples: [
      "Which destination should be the next family trip?",
      "Which snack belongs at every family game night?",
      "Who is most likely to answer the phone on the first ring?",
    ],
    faqs: [
      ["Do we need to use Zoom?", "We can work with the major video meeting platforms. Players use a separate browser link for the games, with no download required."],
      ["Will this work for a small family?", "Yes. We can recommend formats for intimate groups as well as large extended families."],
      ["What if some relatives are not comfortable with technology?", "We provide simple joining instructions and design the experience so guests only need the basic controls on their device."],
      ["Can this become a regular event?", "Yes. We can vary the games and themes for recurring family nights so each event feels fresh."],
    ],
  },
  anniversary: {
    slug: "virtual-anniversary-party",
    eyebrow: "Celebrate the years you have shared",
    title: "Virtual Anniversary Party",
    accent: "Bring the people you love into the celebration.",
    description: "Celebrate a milestone anniversary with a live-hosted online game show featuring favorite memories, music, laughter, and guests joining from anywhere.",
    metaDescription: "Plan a live virtual anniversary party with a professional host, personalized trivia, music, and games for family and friends. From $35 per person.",
    image: "/family-occasion-anniversary.png",
    imageAlt: "A couple celebrating an anniversary with family and friends",
    occasion: "anniversary",
    entryPoint: "family_anniversary_money_page",
    intro: "Whether you are celebrating one year or fifty, we make the couple feel special while giving every guest a comfortable way to join the fun.",
    benefits: [
      "Guests can join from different cities and countries",
      "Approved memories can become personalized questions",
      "Games can be warm, funny, romantic, or a mix",
      "A professional host manages the pace, teams, and finale",
    ],
    games: [
      ["Their Story", "Guests answer playful questions about the couple and the years they have shared."],
      ["Love Songs Through the Years", "A music round shaped around meaningful decades and favorite styles."],
      ["Friends & Family Showdown", "Teams compete with anniversary-themed survey questions."],
    ],
    examples: [
      "Where did the couple first meet?",
      "Which trip would they happily take again tomorrow?",
      "What advice would the family give newlyweds?",
    ],
    faqs: [
      ["Can this be a surprise party?", "Yes. One trusted organizer can provide the approved details while we keep the custom content private from the couple."],
      ["Is this appropriate for a major milestone anniversary?", "Yes. We can shape the show around a 10th, 25th, 50th, or any anniversary that matters to your family."],
      ["Do we need to share personal stories?", "No. Personal stories and photos are optional. We can create a complete anniversary show without private details."],
      ["Can children and grandparents play together?", "Yes. Tell us the age range and we will recommend accessible games and a comfortable pace."],
    ],
  },
  graduation: {
    slug: "virtual-graduation-party",
    eyebrow: "Celebrate the graduate from anywhere",
    title: "Virtual Graduation Party",
    accent: "Give the achievement a proper celebration.",
    description: "Gather classmates, friends, and family for a live-hosted graduation game show filled with school memories, music, friendly competition, and a big finish for the graduate.",
    metaDescription: "Host a live virtual graduation party with personalized trivia, music, all-ages games, and a professional emcee. From $35 per person.",
    image: "/family-occasion-graduation.png",
    imageAlt: "A graduate celebrating outdoors with family",
    occasion: "graduation",
    entryPoint: "family_graduation_money_page",
    intro: "Perfect when loved ones cannot all travel to the ceremony. We take care of the entertainment so the graduate and guests can relax and celebrate together.",
    benefits: [
      "Works for high school, college, graduate school, or professional milestones",
      "Friends and relatives can join from wherever they live",
      "Approved school memories and interests can personalize the show",
      "The graduate gets celebrated without having to run the party",
    ],
    games: [
      ["Graduate Spotlight", "A celebratory round inspired by the graduate's interests and next chapter."],
      ["School Days Trivia", "Friendly questions about classes, campus life, music, and memorable moments."],
      ["Future Forecast", "Guests make funny, positive predictions about what comes next."],
    ],
    examples: [
      "Which class will the graduate still talk about in ten years?",
      "What was their most-used study snack?",
      "Which song belongs on the graduation celebration playlist?",
    ],
    faqs: [
      ["Can several graduates be celebrated together?", "Yes. Share the number of graduates and guests, and we will balance the custom moments so everyone is included."],
      ["Does this work for younger graduates?", "Yes. We adjust the language, pacing, and game choices for the graduate and guest age range."],
      ["Can we include photos or school memories?", "Yes. Approved photos and memories can be included in selected rounds, but they are never required."],
      ["Can guests join after an in-person ceremony?", "Yes. We can help you choose a practical time and show length for guests joining after the ceremony."],
    ],
  },
  multigenerational: {
    slug: "multigenerational-family-games",
    eyebrow: "Games made for every generation",
    title: "Multigenerational Family Games",
    accent: "Kids, parents, and grandparents on the same team.",
    description: "Enjoy a live-hosted online game show designed so different ages, interests, and comfort levels can all contribute without anyone feeling left behind.",
    metaDescription: "Discover live-hosted multigenerational family games for kids, adults, and grandparents. Simple online play, no downloads, from $35 per person.",
    image: "/family-occasion-reunion.png",
    imageAlt: "Several generations of a family laughing together outdoors",
    occasion: "multigenerational",
    formTitle: "Check availability for your family gathering",
    entryPoint: "multigenerational_family_games_money_page",
    intro: "We mix visual, musical, word, memory, and survey-style rounds so no single age group has an unfair advantage. The host explains everything and keeps every household involved.",
    benefits: [
      "Balanced questions give different generations a chance to shine",
      "Simple browser play avoids complicated setup",
      "Teams can pair younger and older relatives together",
      "A live host adjusts the pace when the group needs help",
    ],
    games: [
      ["Generations Battle", "Questions rotate through decades, culture, everyday life, and family-friendly topics."],
      ["Picture This", "Visual clues give readers and non-readers ways to participate together."],
      ["Family Survey Showdown", "Teams guess popular answers instead of relying only on obscure facts."],
    ],
    examples: [
      "Which household chore has changed the most over the years?",
      "Which song can at least three generations sing together?",
      "What snack would every age group choose for movie night?",
    ],
    faqs: [
      ["What ages can participate?", "We can design for children, teens, adults, and older relatives. Share the age range so we can choose the right balance."],
      ["What if one relative is not comfortable with technology?", "Players receive a simple browser link, and the host gives clear instructions before every round."],
      ["Will trivia favor one generation?", "No. We intentionally rotate topics and use team formats so knowledge from different ages becomes an advantage."],
      ["Can households play as teams?", "Yes. We can organize teams by household or mix generations, depending on your group and devices."],
    ],
  },
  reunionGuide: {
    slug: "how-to-plan-a-virtual-family-reunion",
    eyebrow: "A practical virtual reunion guide",
    title: "How to Plan a Virtual Family Reunion",
    accent: "A simple plan that gets relatives to actually join.",
    description: "Use this practical guide to choose a date, include every generation, collect family memories, and build a virtual reunion that feels like a real event—not another long video call.",
    metaDescription: "Learn how to plan a virtual family reunion: choose a date, include every generation, select games, gather memories, and host an easy online celebration.",
    image: "/family-zoom-1.png",
    imageAlt: "A family smiling together on a virtual reunion video call",
    occasion: "reunion",
    formTitle: "Get help planning your virtual family reunion",
    entryPoint: "virtual_family_reunion_planning_guide",
    intro: "The best virtual reunions are shorter, more structured, and easier to join than a normal family video call. Start with the people and date, then add just enough planned activity to keep everyone connected.",
    benefits: [
      "Choose one organizer and a clear RSVP deadline",
      "Plan around time zones and older relatives' technology needs",
      "Use structured games to prevent awkward silences",
      "Collect only the stories and photos relatives approve",
    ],
    planningSteps: [
      ["Choose the guest list and two possible dates", "Ask each household for its time zone and accessibility needs before selecting the final time."],
      ["Pick a simple 60- to 90-minute format", "Leave room for greetings, two or three game rounds, a short family story moment, and a clear ending."],
      ["Send one reliable joining link", "Include a calendar invitation, device guidance, and a contact person for anyone who wants a practice connection."],
      ["Gather optional family details", "Invite relatives to submit approved memories, traditions, photos, favorite songs, and lighthearted facts."],
      ["Assign the hosting job", "A dedicated host should explain rules, move the program along, include quieter guests, and handle scoring."],
      ["Follow up after the reunion", "Share approved photos, answers, or a family trivia keepsake and ask what everyone would enjoy next time."],
    ],
    games: [
      ["Family Story Trivia", "Turn approved memories and traditions into questions relatives can enjoy together."],
      ["Generations Battle", "Give every age group a chance with music, culture, sayings, and moments across decades."],
      ["Family Survey Showdown", "Use playful family prompts that create conversation instead of testing obscure knowledge."],
    ],
    examples: [
      "Which tradition should never disappear?",
      "Which relative has lived in the most places?",
      "What should be the theme of the next reunion?",
    ],
    faqs: [
      ["How long should a virtual family reunion last?", "For most families, 60 to 90 minutes is enough for greetings, games, and stories without creating screen fatigue."],
      ["How far in advance should we plan?", "Four to eight weeks is helpful for larger or international families, although smaller groups can often plan more quickly."],
      ["Which video platform should we use?", "Use the platform your relatives already understand when possible. Teamtastic can work with major meeting platforms, while the games open in a browser."],
      ["Do we need a professional host?", "No, but assigning one person to manage instructions, pacing, and participation makes the reunion much easier. Teamtastic can handle that role for you."],
    ],
  },
};

export function familyOccasion(key) {
  return FAMILY_OCCASIONS[key];
}

export const FAMILY_DEMAND_ROUTES = Object.values(FAMILY_OCCASIONS).map((occasion) => `/${occasion.slug}`);
