// FROZEN SNAPSHOT — NOT LIVE CODE, NOT DEPLOYED, NOT IMPORTED BY ANY RUNTIME FUNCTION.
//
// This is a byte-for-byte copy of the classification logic actually running in the
// deployed `ingest-gmail-replies` edge function (version 20, retrieved via direct
// source inspection on 2026-08-29 for the sole purpose of this certification's
// "Mode A: current production deterministic classifier" comparison). The live repo's
// `supabase/functions/_shared/gmail-classification.ts` has already moved ahead of this
// (9-label enhanced taxonomy) — that is the whole point of this file's existence: to
// preserve exactly what production still runs today so Mode A vs Mode B is a fair,
// reproducible comparison instead of a comparison against documentation or assumption.
//
// Do not edit this file to "improve" it and do not import it from any deploy path.
// If production is redeployed, take a fresh snapshot instead of hand-editing this one.

export type Classification = { classification: string; confidence: number; reason: string; method: "regex" | "llm" };

export const PRODUCTION_FUZZY_CLASSIFICATIONS = ["interested", "not_interested", "referral", "question", "unknown"] as const;

export function productionClassifyHardStop(text: string): Classification | null {
  const has = (pattern: RegExp) => pattern.test(text);

  if (has(/\b(unsubscribe|remove me|stop emailing|do not (?:email|contact)|opt[ -]?out)\b/)) {
    return { classification: "unsubscribe", confidence: 0.99, reason: "explicit opt-out language", method: "regex" };
  }
  if (has(/\b(attorney|legal counsel|cease and desist|lawsuit|litigation|legal action)\b/)) {
    return { classification: "legal", confidence: 0.97, reason: "legal escalation language", method: "regex" };
  }
  if (has(/\b(spam|reported you|harassment|complaint|never contact)\b/)) {
    return { classification: "complaint", confidence: 0.95, reason: "complaint or spam language", method: "regex" };
  }
  if (has(/\b(out of (?:the )?office|automatic reply|auto(?:matic)? response|away from (?:my )?email|on (?:vacation|leave))\b/)) {
    return { classification: "out_of_office", confidence: 0.96, reason: "automatic absence language", method: "regex" };
  }
  return null;
}

export function productionClassifyFuzzyRegex(text: string, body: string): Classification {
  const has = (pattern: RegExp) => pattern.test(text);

  if (has(/\b(not interested|no thank(?:s| you)|not a fit|please pass|we(?:'re| are) all set|do not need)\b/)) {
    return { classification: "not_interested", confidence: 0.94, reason: "explicit negative response", method: "regex" };
  }
  if (has(/\b(reach out to|contact|speak with|forwarded (?:this|your email) to|looping in|better person)\b.{0,80}\b(colleague|manager|team|hr|people|events?|them|her|him)\b/)) {
    return { classification: "referral", confidence: 0.86, reason: "referral language", method: "regex" };
  }
  if (has(/\b(interested|sounds (?:good|great)|let(?:'s| us) (?:talk|chat|meet)|book (?:a )?(?:call|demo)|available (?:to|for)|tell me more|send (?:me )?(?:details|pricing))\b/)) {
    return { classification: "interested", confidence: 0.90, reason: "positive buying language", method: "regex" };
  }
  if (body.includes("?") || has(/\b(question(?:s)?|wondering|how|what|when|where|who|can you|could you|would you|pricing|cost|programs?|services?|more information)\b/)) {
    return { classification: "question", confidence: 0.82, reason: "question language", method: "regex" };
  }
  return { classification: "unknown", confidence: 0.35, reason: "no high-confidence rule matched", method: "regex" };
}

export function productionClassify(subject: string, body: string): Classification {
  const text = `${subject}\n${body}`.toLowerCase().slice(0, 30_000);
  return productionClassifyHardStop(text) ?? productionClassifyFuzzyRegex(text, body);
}
