import Link from "next/link";
import {getSupabaseAdmin} from "@/lib/server/supabase-admin";
import {Card,Empty,buttonClass,formatDate,inputClass} from "../../office-ui";
import {configureWarmRelationshipSignals,recordWarmRelationshipSignal,reviewWarmRelationshipSignal} from "../../actions";

const labels={job_change:"Job change",new_people_ops_hire:"New People Ops hire",promotion:"Promotion",closed_lost_reactivation:"Closed-lost reactivation",past_champion:"Past champion"};

export default async function WarmSignalsPage({searchParams}){
  const params=await searchParams,db=getSupabaseAdmin();
  const [{data:config},{data:signals},{data:prospects}]=await Promise.all([
    db.from("system_config").select("warm_relationship_signals_enabled,closed_lost_reactivation_days").eq("id",true).single(),
    db.from("warm_relationship_signals").select("id,prospect_id,signal_type,evidence,source,source_url,strength,status,observed_at,created_at,prospects(full_name,email,job_title),companies(name)").order("observed_at",{ascending:false}).limit(100),
    db.from("prospects").select("id,full_name,email,job_title").not("email","is",null).not("status","in",'(suppressed,disqualified)').order("updated_at",{ascending:false}).limit(250),
  ]);
  const rows=signals||[],open=rows.filter(x=>x.status==="new");
  return <div className="space-y-8">
    {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?`Action blocked: ${params.error.replaceAll("_"," ")}.`:"Warm-signal action completed."}</p>}
    <div><h2 className="text-3xl font-bold">Warm relationship signals</h2><p className="mt-2 text-slate-400">Prioritize timely relationship moments without automatic outreach. Every signal creates a human review task.</p></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card title="Module"><p className={`text-2xl font-bold ${config?.warm_relationship_signals_enabled?"text-emerald-300":"text-amber-300"}`}>{config?.warm_relationship_signals_enabled?"Enabled":"Paused"}</p></Card><Card title="Needs review"><p className="text-3xl font-bold">{open.length}</p></Card><Card title="Signals recorded"><p className="text-3xl font-bold">{rows.length}</p></Card></div>
    <Card title="Automation settings"><form action={configureWarmRelationshipSignals} className="grid gap-4 md:grid-cols-[1fr_220px_auto]"><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="enabled" defaultChecked={config?.warm_relationship_signals_enabled}/> Enable signal intake and daily closed-lost review</label><label className="text-sm">Reactivate after days<input className={inputClass} name="reactivation_days" type="number" min="14" max="730" defaultValue={config?.closed_lost_reactivation_days||90}/></label><button className={`${buttonClass} self-end`}>Save settings</button></form><p className="mt-3 text-xs text-slate-500">This switch creates tasks and score evidence only. It never sends outreach.</p></Card>
    <Card title="Record a trusted signal"><form action={recordWarmRelationshipSignal} className="grid gap-4 lg:grid-cols-2"><label className="text-sm">Person<select required className={inputClass} name="prospect_id" defaultValue=""><option value="" disabled>Select a prospect</option>{(prospects||[]).map(p=><option key={p.id} value={p.id}>{p.full_name||p.email} — {p.job_title||p.email}</option>)}</select></label><label className="text-sm">Signal type<select className={inputClass} name="signal_type">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">Observed at<input className={inputClass} name="observed_at" type="datetime-local"/></label><label className="text-sm">Evidence URL (optional)<input className={inputClass} name="source_url" type="url" placeholder="https://..."/></label><label className="text-sm lg:col-span-2">What changed?<textarea required minLength={5} rows={3} className={inputClass} name="evidence" placeholder="Example: Promoted to VP of People; public profile reviewed August 10."/></label><button className={buttonClass}>Create review task</button></form></Card>
    <Card title="Signal review queue" count={rows.length}>{!rows.length?<Empty>No warm relationship signals have been recorded.</Empty>:<div className="space-y-4">{rows.map(row=>{const p=Array.isArray(row.prospects)?row.prospects[0]:row.prospects,c=Array.isArray(row.companies)?row.companies[0]:row.companies;return <div key={row.id} className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{labels[row.signal_type]} · <Link className="text-purple-300" href={`/office/prospects/${row.prospect_id}`}>{p?.full_name||p?.email||"Prospect"}</Link></p><p className="mt-1 text-sm text-slate-400">{c?.name||p?.job_title||"Company not linked"} · {Math.round(Number(row.strength)*100)}% strength · {formatDate(row.observed_at)}</p><p className="mt-3 text-sm">{row.evidence}</p>{row.source_url&&<a className="mt-2 inline-block text-xs text-sky-300" href={row.source_url} target="_blank" rel="noreferrer">Open evidence ↗</a>}</div><span className="rounded-full bg-white/5 px-3 py-1 text-xs uppercase tracking-wide">{row.status}</span></div>{row.status==="new"&&<div className="mt-4 flex gap-2">{[["reviewed","Keep for follow-up"],["actioned","Mark actioned"],["dismissed","Dismiss"]].map(([status,label])=><form action={reviewWarmRelationshipSignal} key={status}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value={status}/><button className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/5">{label}</button></form>)}</div>}</div>})}</div>}</Card>
  </div>;
}
