import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "bundle.js",
    "*.js",
    // Generated by `npm run test:coverage` (@vitest/coverage-v8's html
    // reporter) — vendored third-party assets, not project source.
    "coverage/**",
  ]),
]);

export default eslintConfig;
