import {getSupabaseAdmin} from "@/lib/server/supabase-admin";
import {Card,buttonClass,formatDate,inputClass} from "../../office-ui";
import {transitionB2bLaunch} from "../../actions";

const phases=["inbound_pilot","proposal_pilot","live"];
const messages={launch_readiness_blocked:"Launch Control has a blocker. Resolve it before activation.",certification_required:"A passing Phase 1 certification is required.",inbound_pilot_required:"Complete the inbound pilot step first.",proposal_pilot_required:"Enable the proposal pilot before outbound.",deliverability_auto_pause_active:"Outbound is automatically paused for deliverability. Investigate before resuming."};
function Step({number,title,detail,active,complete,children}){return <div className={`rounded-2xl border p-5 ${complete?"border-emerald-400/20 bg-emerald-500/10":active?"border-purple-400/30 bg-purple-500/10":"border-white/10 bg-white/[0.03] opacity-70"}`}><p className="text-xs font-bold uppercase tracking-wider text-purple-300">Step {number}</p><h3 className="mt-1 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-300">{detail}</p>{children&&<div className="mt-4">{children}</div>}</div>}
export default async function ActivationPage({searchParams}){const params=await searchParams,db=getSupabaseAdmin();const [stateResult,configResult,readyResult,certResult,historyResult]=await Promise.all([db.from("b2b_launch_state").select("*").eq("id",true).single(),db.from("system_config").select("master_enabled,gmail_ingestion_enabled,daily_report_enabled,proposal_email_enabled,prospecting_enabled,sequence_followups_enabled,daily_prospecting_cap,outbound_auto_paused").eq("id",true).single(),db.from("launch_readiness_snapshots").select("id,status,blocker_count,warning_count,created_at").order("created_at",{ascending:false}).limit(1).maybeSingle(),db.from("b2b_certification_runs").select("id,status,passed_count,failed_count,completed_at").order("completed_at",{ascending:false}).limit(1).maybeSingle(),db.from("b2b_launch_history").select("*").order("created_at",{ascending:false}).limit(20)]);const state=stateResult.data||{phase:"off"},config=configResult.data,ready=readyResult.data,cert=certResult.data,history=historyResult.data||[];const preflight=ready?.status!=="blocked"&&ready?.blocker_count===0&&cert?.status==="passed";const error=params?.error?messages[params.error]||params.error.replaceAll("_"," "):null;return <div className="space-y-8">
  {(params?.success||error)&&<p className={`rounded-xl p-4 text-sm ${error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{error||"Launch configuration updated successfully."}</p>}
  <div><h2 className="text-3xl font-bold">Controlled B2B activation</h2><p className="mt-2 text-slate-400">A guarded, staged workflow with preflight enforcement, conservative limits, emergency pause, and full rollback history.</p></div>
  <section className={`rounded-2xl border p-6 ${state.phase==="live"?"border-emerald-400/30 bg-emerald-500/10":state.phase==="paused"?"border-red-400/30 bg-red-500/10":"border-purple-400/30 bg-purple-500/10"}`}><p className="text-sm font-bold uppercase tracking-[0.2em]">Current phase</p><h3 className="mt-2 text-3xl font-bold capitalize">{state.phase.replaceAll("_"," ")}</h3>{state.launched_at&&<p className="mt-2 text-sm text-slate-300">Started {formatDate(state.launched_at)} by {state.launched_by}</p>}{state.pause_reason&&<p className="mt-2 text-sm text-red-200">{state.pause_reason}</p>}</section>
  <div className="grid gap-4 sm:grid-cols-2"><Card title="Launch Control"><p className={`text-2xl font-bold ${ready?.blocker_count===0?"text-emerald-300":"text-red-300"}`}>{ready?.blocker_count===0?"Healthy":"Blocked"}</p><p className="mt-2 text-sm text-slate-400">{ready?.blocker_count??"—"} blockers · {ready?.warning_count??"—"} warnings · {formatDate(ready?.created_at)}</p></Card><Card title="Phase 1 certification"><p className={`text-2xl font-bold ${cert?.status==="passed"?"text-emerald-300":"text-red-300"}`}>{cert?.status||"Missing"}</p><p className="mt-2 text-sm text-slate-400">{cert?.passed_count||0} passed · {cert?.failed_count||0} failed · {formatDate(cert?.completed_at)}</p></Card></div>
  <div className="space-y-4"><Step number="1" title="Inbound pilot" detail="Enables the master automation, Gmail reply ingestion, and daily reporting. Proposals, prospecting, and automated follow-ups remain off." active={["off","paused","rolled_back"].includes(state.phase)} complete={phases.includes(state.phase)}>{["off","paused","rolled_back"].includes(state.phase)&&<form action={transitionB2bLaunch}><input type="hidden" name="launch_action" value="begin_pilot"/><button disabled={!preflight} className={`${buttonClass} disabled:opacity-40`}>Begin inbound pilot</button>{!preflight&&<p className="mt-2 text-xs text-red-300">Passing preflight and certification are required.</p>}</form>}</Step>
  <Step number="2" title="Proposal pilot" detail="Enables only human-approved proposal sending. Cold prospecting remains off." active={state.phase==="inbound_pilot"} complete={["proposal_pilot","live"].includes(state.phase)}>{state.phase==="inbound_pilot"&&<form action={transitionB2bLaunch}><input type="hidden" name="launch_action" value="enable_proposals"/><button className={buttonClass}>Enable proposal pilot</button></form>}</Step>
  <Step number="3" title="Low-volume outbound" detail="Enables prospecting and sequence follow-ups with a hard initial cap of no more than 10 messages per day." active={state.phase==="proposal_pilot"} complete={state.phase==="live"}>{state.phase==="proposal_pilot"&&<form action={transitionB2bLaunch} className="flex flex-wrap items-end gap-3"><input type="hidden" name="launch_action" value="enable_outbound"/><label className="text-sm">Initial daily cap<input className={inputClass} type="number" name="daily_cap" min="1" max="10" defaultValue="5"/></label><button className={buttonClass}>Enable low-volume outbound</button></form>}</Step></div>
  <Card title="Live switch state"><div className="grid gap-2 sm:grid-cols-2">{[["Master",config?.master_enabled],["Gmail ingestion",config?.gmail_ingestion_enabled],["Daily reporting",config?.daily_report_enabled],["Proposal email",config?.proposal_email_enabled],["Prospecting",config?.prospecting_enabled],["Sequence follow-ups",config?.sequence_followups_enabled]].map(([name,on])=><p key={name} className="flex justify-between rounded-lg bg-white/5 p-3 text-sm"><span>{name}</span><strong className={on?"text-emerald-300":"text-slate-400"}>{on?"On":"Off"}</strong></p>)}</div><p className="mt-3 text-xs text-slate-500">Prospecting cap: {config?.daily_prospecting_cap||0} per day{config?.outbound_auto_paused?" · automatic deliverability pause is active":""}.</p></Card>
  <div className="grid gap-6 lg:grid-cols-2"><Card title="Emergency pause"><p className="mb-4 text-sm text-slate-300">Immediately disables the master switch, proposals, prospecting, and sequence follow-ups. It does not delete queued work or history.</p><form action={transitionB2bLaunch}><input type="hidden" name="launch_action" value="pause"/><label className="text-sm">Reason<input name="reason" required placeholder="Why are we pausing?" className={inputClass}/></label><button className="mt-3 rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold hover:bg-red-500">Emergency pause</button></form></Card><Card title="Rollback"><p className="mb-4 text-sm text-slate-300">Restores the exact automation settings captured immediately before the inbound pilot began.</p><form action={transitionB2bLaunch}><input type="hidden" name="launch_action" value="rollback"/><input type="hidden" name="reason" value="Operator requested pre-launch rollback"/><button className="rounded-lg border border-amber-400/30 px-4 py-2 text-sm font-semibold text-amber-200 hover:bg-amber-500/10">Restore pre-launch configuration</button></form><p className="mt-3 text-xs text-slate-500">Rollback does not remove leads, deals, tasks, or certification evidence.</p></Card></div>
  <Card title="Activation history"><div className="space-y-2">{history.map(item=><div key={item.id} className="rounded-lg bg-white/5 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{item.from_phase.replaceAll("_"," ")} → {item.to_phase.replaceAll("_"," ")}</strong><span className="text-slate-400">{formatDate(item.created_at)}</span></div><p className="mt-1 text-slate-400">{item.action.replaceAll("_"," ")} · {item.actor}{item.reason?` · ${item.reason}`:""}</p></div>)}{!history.length&&<p className="text-sm text-slate-400">No activation changes have been made.</p>}</div></Card>
  <Card title="Recovery sequence"><ol className="list-decimal space-y-2 pl-5 text-sm text-slate-300"><li>Use Emergency pause at the first sign of incorrect sending, reply handling, or deliverability degradation.</li><li>Open Launch Control and the incident source; resolve every red blocker.</li><li>Use rollback if the prior automation configuration is required.</li><li>Run Phase 1 certification again before restarting the inbound pilot.</li></ol></Card>
  </div>}
