import {getSupabaseAdmin} from "@/lib/server/supabase-admin";
import {Card,buttonClass,formatDate} from "../../office-ui";
import {startB2bCertification,verifyB2bCertification} from "../../actions";

export default async function CertificationPage({searchParams}){const params=await searchParams,db=getSupabaseAdmin();const {data:runs=[]}=await db.from("b2b_certification_runs").select("*").order("started_at",{ascending:false}).limit(10);const selected=runs.find(x=>x.id===params?.run)||runs[0];return <div className="space-y-8">
  {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-amber-500/10 text-amber-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error==="crm_sync_pending"?"CRM synchronization is still finishing. Wait a few seconds, then verify again.":params.error?"The certification needs attention. Review the checkpoints below.":params.success==="passed"?"Phase 1 certification passed.":"Synthetic leads created. Verify once CRM synchronization finishes."}</p>}
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Phase 1 certification</h2><p className="mt-2 text-slate-400">Repeatable lead-to-client testing across all holiday capture paths. Synthetic records are retained for audit evidence; external sends are always suppressed.</p></div><form action={startB2bCertification}><button className={buttonClass}>Start safe certification</button></form></div>
  {selected?<><div className="grid gap-4 sm:grid-cols-4"><Card title="Status"><p className={`text-3xl font-bold ${selected.status==="passed"?"text-emerald-300":selected.status==="failed"?"text-red-300":"text-amber-300"}`}>{selected.status}</p></Card><Card title="Passed"><p className="text-3xl font-bold text-emerald-300">{selected.passed_count}</p></Card><Card title="Failed"><p className="text-3xl font-bold text-red-300">{selected.failed_count}</p></Card><Card title="External sends"><p className="text-3xl font-bold text-emerald-300">{selected.external_messages_sent}</p></Card></div>
  {selected.status==="running"&&<form action={verifyB2bCertification}><input type="hidden" name="run_id" value={selected.id}/><button className={buttonClass}>Verify CRM, deposit, and portal handoff</button></form>}
  <Card title="Checkpoint results"><div className="space-y-3">{(selected.checkpoints||[]).map(check=><div key={check.key} className={`rounded-xl border p-4 ${check.passed?"border-emerald-400/20 bg-emerald-500/10":"border-red-400/20 bg-red-500/10"}`}><div className="flex justify-between gap-3"><p className="font-semibold">{check.label}</p><span className={check.passed?"text-emerald-300":"text-red-300"}>{check.passed?"Passed":"Failed"}</span></div><p className="mt-1 text-sm text-slate-300">{check.detail}</p></div>)}{!selected.checkpoints?.length&&<p className="text-sm text-slate-400">Synthetic leads have been submitted. Verification checks appear here after CRM synchronization.</p>}</div></Card></>:<Card title="No certification runs"><p className="text-sm text-slate-400">Start the first safe end-to-end certification.</p></Card>}
  <Card title="Recent evidence"><div className="space-y-2">{runs.map(run=><p key={run.id} className="rounded-lg bg-white/5 p-3 text-sm"><strong>{run.status}</strong><span className="text-slate-400"> · {run.passed_count} passed · {run.failed_count} failed · {formatDate(run.started_at)} · {run.started_by}</span></p>)}</div></Card>
  <p className="text-xs text-slate-500">Certification records use example.com addresses and a synthetic_test marker. The notification function performs CRM synchronization, records both expected notification paths as test-suppressed, and exits before quota reservation or provider access.</p>
  </div>}
