import { getSupabaseAdmin } from "@/lib/server/supabase-admin";
import { Card,buttonClass,inputClass } from "../../office-ui";
import { prepareDistributionQueue,reviewDistributionItem } from "../../actions";

export default async function DistributionPage({searchParams}){const params=await searchParams;const db=getSupabaseAdmin();const {data:items}=await db.from("distribution_items").select("*").neq("status","archived").order("created_at",{ascending:false}).limit(50);return <div className="space-y-8">
  {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-300":"bg-emerald-500/10 text-emerald-300"}`}>{params.error?"The distribution action could not be completed.":"Distribution queue updated."}</p>}
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Campaign distribution</h2><p className="mt-2 text-slate-400">Audience-specific drafts with tracked links. Nothing posts or sends automatically.</p></div><form action={prepareDistributionQueue}><button className={buttonClass}>Prepare this month&apos;s drafts</button></form></div>
  <div className="grid gap-4 sm:grid-cols-3"><Card title="Drafts"><p className="text-3xl font-bold text-purple-300">{(items||[]).filter(x=>x.status==="draft").length}</p></Card><Card title="Ready / scheduled"><p className="text-3xl font-bold text-sky-300">{(items||[]).filter(x=>["approved","scheduled"].includes(x.status)).length}</p></Card><Card title="Published"><p className="text-3xl font-bold text-emerald-300">{(items||[]).filter(x=>x.status==="published").length}</p></Card></div>
  <div className="space-y-5">{(items||[]).map(item=><Card key={item.id} title={`${item.channel} · ${item.title}`}><form action={reviewDistributionItem} className="space-y-3"><input type="hidden" name="id" value={item.id}/><div className="flex flex-wrap gap-2 text-xs text-slate-400"><span>{item.audience}</span><span>·</span><span>{item.status}</span><span>·</span><span>{item.visitors} visitors / {item.leads} leads</span></div><textarea name="body_text" rows={6} defaultValue={item.body_text} readOnly={item.status!=="draft"} className={inputClass}/><label className="block text-xs text-slate-400">Tracked destination<input readOnly value={item.tracked_url} className={inputClass}/></label>{item.status==="approved"&&<label className="block text-xs text-slate-400">Planned publish time<input name="scheduled_for" type="datetime-local" className={inputClass}/></label>}{["approved","scheduled"].includes(item.status)&&<label className="block text-xs text-slate-400">Published URL<input name="published_url" type="url" placeholder="https://..." className={inputClass}/></label>}<div className="flex flex-wrap gap-2">{item.status==="draft"&&<><button name="decision" value="approve" className={buttonClass}>Approve draft</button><button name="decision" value="reject" className="rounded-lg border border-white/10 px-4 py-2 text-sm">Reject</button></>}{item.status==="approved"&&<button name="decision" value="schedule" className={buttonClass}>Schedule manually</button>}{["approved","scheduled"].includes(item.status)&&<button name="decision" value="published" className={buttonClass}>Mark published</button>}</div></form></Card>)}{!items?.length&&<p className="text-sm text-slate-400">No drafts yet.</p>}</div>
</div>}
