import { getOfficeDb } from "@/lib/server/office-auth";
import {Card,Empty,ProspectLink,buttonClass,formatDate,inputClass} from "../../office-ui";
import {refreshProductionIncidents,updateProductionIncident} from "../../actions";

const severityTone={critical:"border-red-400/40 bg-red-500/10",high:"border-orange-400/30 bg-orange-500/10",medium:"border-amber-400/20 bg-amber-500/10",low:"border-white/10 bg-white/5"};
export default async function IncidentsPage({searchParams}){const params=await searchParams,db=(await getOfficeDb()).db;const [incidentsResult,updatesResult]=await Promise.all([db.from("production_incidents").select("*").order("last_seen_at",{ascending:false}).limit(100),db.from("production_incident_updates").select("*").order("created_at",{ascending:false}).limit(300)]);const incidents=incidentsResult.data||[],updates=updatesResult.data||[],open=incidents.filter(x=>x.status!=="resolved"),critical=open.filter(x=>x.severity==="critical"),high=open.filter(x=>x.severity==="high"),monitoring=open.filter(x=>x.status==="monitoring");return <div className="space-y-8">
  {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?"The incident action could not be completed.":"Incident Center updated."}</p>}
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Production incidents</h2><p className="mt-2 text-slate-400">One operational record for failures across jobs, webhooks, notifications, email, Stripe, and conversion pages.</p></div><form action={refreshProductionIncidents}><button className={buttonClass}>Scan production now</button></form></div>
  <div className="grid gap-4 sm:grid-cols-4"><Card title="Open"><p className="text-3xl font-bold">{open.length}</p></Card><Card title="Critical"><p className={`text-3xl font-bold ${critical.length?"text-red-300":"text-emerald-300"}`}>{critical.length}</p></Card><Card title="High"><p className={`text-3xl font-bold ${high.length?"text-orange-300":"text-emerald-300"}`}>{high.length}</p></Card><Card title="Monitoring"><p className="text-3xl font-bold text-amber-300">{monitoring.length}</p></Card></div>
  <Card title="Active incidents" count={open.length} tone={critical.length?"red":open.length?"gold":"green"}><div className="space-y-4">{open.map(item=>{const timeline=updates.filter(x=>x.incident_id===item.id);return <div key={item.id} className={`rounded-2xl border p-5 ${severityTone[item.severity]}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{item.severity} · {item.category.replaceAll("_"," ")} · {item.status}</p><h3 className="mt-1 text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm text-slate-300">{item.description}</p>{item.prospect_id&&<div className="mt-2"><ProspectLink id={item.prospect_id}/></div>}<p className="mt-2 text-xs text-slate-500">Owner: {item.owner} · seen {item.occurrences} time{item.occurrences===1?"":"s"} · last {formatDate(item.last_seen_at)}</p></div><span className="rounded-full bg-black/20 px-3 py-1 text-xs font-bold uppercase">{item.severity}</span></div>
    <form action={updateProductionIncident} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="incident_id" value={item.id}/><label className="text-sm">Owner<input name="owner" defaultValue={item.owner} className={inputClass}/></label><label className="text-sm">Recovery note<input name="note" required placeholder="What was checked or changed?" className={inputClass}/></label><label className="text-sm">Status<select name="status" className={inputClass}><option value="acknowledged">Acknowledged</option><option value="monitoring">Monitoring</option><option value="resolved">Resolved</option></select></label><button className={`${buttonClass} sm:col-span-3 sm:justify-self-start`}>Record update</button></form>
    {timeline.length>0&&<details className="mt-4 text-sm"><summary className="cursor-pointer text-slate-300">Recovery history ({timeline.length})</summary><div className="mt-2 space-y-2">{timeline.map(update=><p key={update.id} className="rounded-lg bg-black/10 p-3"><strong>{update.update_type.replaceAll("_"," ")}</strong> · {update.actor} · {formatDate(update.created_at)}<span className="mt-1 block text-slate-400">{update.note||"No note"}</span></p>)}</div></details>}</div>})}{!open.length&&<Empty>No unresolved production incidents.</Empty>}</div></Card>
  <Card title="Recently resolved"><div className="space-y-2">{incidents.filter(x=>x.status==="resolved").slice(0,30).map(item=><div key={item.id} className="rounded-lg bg-white/5 p-3 text-sm"><div className="flex flex-wrap justify-between gap-3"><strong>{item.title}</strong><span className="text-emerald-300">Resolved {formatDate(item.resolved_at)}</span></div><p className="mt-1 text-slate-400">{item.resolution||"Resolved by operator."}</p></div>)}{!incidents.some(x=>x.status==="resolved")&&<Empty>No resolved incidents recorded yet.</Empty>}</div></Card>
  <p className="text-xs text-slate-500">The monitor runs every five minutes. High and critical incidents also create one deduplicated urgent Office task. Resolving an incident never deletes the underlying provider, CRM, payment, or job evidence.</p>
  </div>}
