import Link from "next/link";
import { getOfficeDb } from "@/lib/server/office-auth";
import {Card,buttonClass,formatDate} from "../../office-ui";
import {refreshDailyGrowthAgenda} from "../../actions";
const tones={urgent:"border-red-400/20 bg-red-500/10",high:"border-amber-400/20 bg-amber-500/10",normal:"border-white/10 bg-white/5"};
export default async function RoadmapPage({searchParams}){const params=await searchParams;const db=(await getOfficeDb()).db;const {data:agenda}=await db.from("daily_growth_agendas").select("*").order("agenda_date",{ascending:false}).limit(1).maybeSingle();const summary=agenda?.summary||{},items=agenda?.items||[];return <div className="space-y-8">
  {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-300":"bg-emerald-500/10 text-emerald-300"}`}>{params.error?"The agenda could not be refreshed.":"Today’s agenda is current."}</p>}
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Daily growth agenda</h2><p className="mt-2 text-slate-400">The highest-value sales and growth decisions across every Teamtastic queue.</p></div><form action={refreshDailyGrowthAgenda}><button className={buttonClass}>Refresh priorities</button></form></div>
  {!agenda?<Card title="No agenda yet"><p className="text-sm text-slate-400">Generate today’s ranked agenda.</p></Card>:<><div className="grid gap-4 sm:grid-cols-4"><Card title="Priorities"><p className="text-3xl font-bold">{summary.total||0}</p></Card><Card title="Urgent"><p className="text-3xl font-bold text-red-300">{summary.urgent||0}</p></Card><Card title="Sales"><p className="text-3xl font-bold text-sky-300">{summary.sales||0}</p></Card><Card title="Growth"><p className="text-3xl font-bold text-purple-300">{summary.growth||0}</p></Card></div>
  <div className="space-y-3">{items.map((item,index)=><Link href={item.href} key={`${item.source}-${index}`} className={`block rounded-2xl border p-5 transition hover:border-purple-400/40 ${tones[item.priority]}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-purple-300">{item.priority} · {item.source.replaceAll("_"," ")}</p><h3 className="mt-1 text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm text-slate-300">{item.detail}</p></div>{item.due_at&&<span className="text-xs text-slate-400">Due {formatDate(item.due_at)}</span>}</div></Link>)}{!items.length&&<p className="rounded-xl bg-emerald-500/10 p-5 text-emerald-300">No urgent growth or sales actions are waiting.</p>}</div><p className="text-xs text-slate-500">Generated {new Date(agenda.generated_at).toLocaleString()}. Completing work in the linked source queue removes it from the next refresh.</p></>}
</div>}
