import {getSupabaseAdmin} from "@/lib/server/supabase-admin";
import {Card,buttonClass} from "../../office-ui";
import {refreshAudienceIntelligence} from "../../actions";
const pct=v=>v==null?"—":`${Math.round(Number(v)*100)}%`;
const labels={occasion:"Occasions",team_size:"Team sizes",budget:"Budget ranges",decision_timeline:"Decision timing",time_zone:"Time zones",source:"Lead sources"};
export default async function AudiencePage({searchParams}){const params=await searchParams;const db=getSupabaseAdmin();const {data:snapshot}=await db.from("audience_snapshots").select("*").order("snapshot_date",{ascending:false}).limit(1).maybeSingle();const summary=snapshot?.summary||{},segments=snapshot?.segments||{};return <div className="space-y-8">
  {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-300":"bg-emerald-500/10 text-emerald-300"}`}>{params.error?"Audience intelligence could not be refreshed.":"Audience intelligence refreshed."}</p>}
  <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Audience intelligence</h2><p className="mt-2 text-slate-400">First-party demand patterns and pipeline outcomes from the last 90 days. No customer message text is exposed here.</p></div><form action={refreshAudienceIntelligence}><button className={buttonClass}>Refresh now</button></form></div>
  {!snapshot?<Card title="No snapshot yet"><p className="text-sm text-slate-400">Generate the first audience snapshot.</p></Card>:<><div className="grid gap-4 sm:grid-cols-3"><Card title="Leads"><p className="text-3xl font-bold text-purple-300">{summary.leads||0}</p></Card><Card title="Progressed"><p className="text-3xl font-bold text-sky-300">{summary.progressed||0} <span className="text-base text-slate-500">{pct(summary.progression_rate)}</span></p></Card><Card title="Converted"><p className="text-3xl font-bold text-emerald-300">{summary.converted||0} <span className="text-base text-slate-500">{pct(summary.conversion_rate)}</span></p></Card></div>
  <Card title="Recommended audience actions"><div className="space-y-3">{(snapshot.recommendations||[]).map((r,i)=><div key={i} className="rounded-lg bg-white/5 p-4"><p className="font-semibold">{r.action}</p><p className="mt-1 text-xs uppercase text-purple-300">{r.priority} priority</p></div>)}</div></Card>
  <div className="grid gap-5 lg:grid-cols-2">{Object.entries(labels).map(([key,label])=><Card key={key} title={label}><div className="space-y-2">{(segments[key]||[]).slice(0,8).map(row=><div key={row.value} className="grid grid-cols-[1fr_auto] gap-4 rounded-lg bg-white/5 p-3 text-sm"><span>{row.value}</span><span className="text-slate-400">{row.leads} leads · {pct(row.progression_rate)} progressed</span></div>)}</div></Card>)}</div>
  <Card title="Closed-lost themes"><div className="space-y-2">{(snapshot.objections||[]).map(row=><p key={row.category} className="rounded-lg bg-white/5 p-3 text-sm"><span className="font-semibold">{row.category}</span><span className="text-slate-400"> · {row.occurrences}</span></p>)}{!snapshot.objections?.length&&<p className="text-sm text-slate-400">No closed-lost themes in this period.</p>}</div></Card>
  <p className="text-xs text-slate-500">Generated {new Date(snapshot.generated_at).toLocaleString()} · {snapshot.period_start} through {snapshot.period_end}. Objections are categorized; raw notes are not displayed.</p></>}
</div>}
