import {getSupabaseAdmin} from "@/lib/server/supabase-admin";
import {Card,Empty,ProspectLink,buttonClass,formatDate,inputClass} from "../../office-ui";
import {approveAndSendSalesResponse,createSalesResponseDraft} from "../../actions";

const holidaySources=["holiday_party_money_page","year_end_celebration_page","large_holiday_event_page"];
const packageFor=lead=>lead.package_interest==="large-event-production"||/150|200|300/.test(lead.team_size||"")?"Large-Group Holiday Production":lead.package_interest==="custom-year-in-review"?"Custom Year-in-Review Show":"Hosted Teamtastic Holiday Game Show";

export default async function RespondPage({searchParams}){
  const params=await searchParams,db=getSupabaseAdmin(),now=new Date().toISOString();
  const [{data:leads},{data:drafts},{data:holds},{data:deals},{data:revisions}]=await Promise.all([
    db.from("leads").select("id,prospect_id,name,email,company,phone,team_size,vibe,occasion,preferred_event_date,alternate_event_date,event_timezone,preferred_time,budget_range,package_interest,decision_timeline,lead_score,lead_score_reasons,context,created_at").in("lead_source",holidaySources).order("lead_score",{ascending:false}).limit(50),
    db.from("sales_response_drafts").select("*").in("status",["draft","send_failed","sending"]).order("created_at",{ascending:false}).limit(50),
    db.from("event_capacity_holds").select("id,lead_id,status,starts_at,ends_at,expires_at").in("status",["tentative","confirmed"]).or(`expires_at.is.null,expires_at.gt.${now}`),
    db.from("deals").select("id,prospect_id,title,stage,outcome,next_action,next_action_due_at,package_name,expected_value").eq("outcome","open"),
    db.from("sales_response_revisions").select("id,response_id,revision_type,actor,created_at,metadata").order("created_at",{ascending:false}).limit(300),
  ]);
  const rows=(leads||[]).filter(x=>!x.context?.synthetic_test),leadById=new Map(rows.map(x=>[x.id,x])),dealByProspect=new Map((deals||[]).map(x=>[x.prospect_id,x]));
  const openDrafts=drafts||[],responded=new Set(openDrafts.map(x=>x.lead_id));
  return <div className="space-y-8">
    {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?`Response action stopped: ${String(params.error).replaceAll("_"," ")}.`:params.success==="response_sent"?"Response approved, delivered, and recorded.":"Response draft created for review."}</p>}
    <div><h2 className="text-3xl font-bold">Sales response workspace</h2><p className="mt-2 text-slate-400">Understand, choose the next step, edit, approve, and respond without searching across the CRM.</p></div>
    <div className="grid gap-4 sm:grid-cols-4"><Card title="Qualified leads"><p className="text-3xl font-bold">{rows.length}</p></Card><Card title="High priority"><p className="text-3xl font-bold text-emerald-300">{rows.filter(x=>x.lead_score>=70).length}</p></Card><Card title="Drafts awaiting approval"><p className="text-3xl font-bold text-amber-300">{openDrafts.filter(x=>x.status!=="sending").length}</p></Card><Card title="Availability held"><p className="text-3xl font-bold text-purple-300">{(holds||[]).length}</p></Card></div>
    <Card title="Leads ready for a response" count={rows.length}><div className="space-y-4">{rows.map(lead=>{const hold=(holds||[]).find(x=>x.lead_id===lead.id),deal=dealByProspect.get(lead.prospect_id),pkg=deal?.package_name||packageFor(lead);return <div key={lead.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div>{lead.prospect_id?<ProspectLink id={lead.prospect_id} name={lead.name} email={lead.email}/>:<strong>{lead.name}</strong>}<p className="mt-1 text-sm text-slate-300">{lead.company||"Company missing"} · {lead.team_size||"size missing"} · score {lead.lead_score??0}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${hold?"bg-emerald-500/15 text-emerald-200":"bg-amber-500/15 text-amber-200"}`}>{hold?`${hold.status.toUpperCase()} UNTIL ${hold.expires_at?formatDate(hold.expires_at):"EVENT"}`:"CAPACITY NOT HELD"}</span></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Requested schedule" value={[lead.preferred_event_date,lead.preferred_time,lead.event_timezone].filter(Boolean).join(" · ")||"Missing"}/><Summary label="Budget" value={lead.budget_range||"Missing"}/><Summary label="Decision timing" value={lead.decision_timeline||"Missing"}/><Summary label="Recommended package" value={pkg}/></div>
      {deal&&<p className="mt-3 text-xs text-slate-500">Deal: {deal.stage.replaceAll("_"," ")} · Next: {deal.next_action||"not set"} {deal.next_action_due_at?`by ${formatDate(deal.next_action_due_at)}`:""}</p>}
      <div className="mt-4 flex flex-wrap gap-2">{[["availability","Draft availability response"],["discovery_call","Draft call invitation"],["proposal","Draft proposal response"],["deposit_request","Draft deposit request"]].map(([type,label])=><form action={createSalesResponseDraft} key={type}><input type="hidden" name="lead_id" value={lead.id}/><input type="hidden" name="response_type" value={type}/><button className={type==="availability"?buttonClass:"rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5"}>{label}</button></form>)}</div>{responded.has(lead.id)&&<p className="mt-2 text-xs text-purple-300">An editable response draft is waiting below.</p>}
    </div>})}{!rows.length&&<Empty>No qualified holiday leads are waiting.</Empty>}</div></Card>
    <Card title="Human approval queue" count={openDrafts.length} tone={openDrafts.length?"gold":"green"}><div className="space-y-5">{openDrafts.map(draft=>{const lead=leadById.get(draft.lead_id),timeline=(revisions||[]).filter(x=>x.response_id===draft.id);return <form action={approveAndSendSalesResponse} key={draft.id} className="rounded-2xl border border-amber-400/20 bg-amber-500/5 p-5"><input type="hidden" name="id" value={draft.id}/><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-purple-300">{draft.response_type.replaceAll("_"," ")} · {draft.status}</p><strong>{lead?.name||draft.recipient_email}</strong><p className="text-xs text-slate-500">{draft.recipient_email} · {draft.recommended_package}</p></div><span className="text-xs text-slate-400">Generated {formatDate(draft.created_at)}</span></div><label className="mt-4 block text-sm">Subject<input required name="subject" defaultValue={draft.subject} className={inputClass}/></label><label className="mt-3 block text-sm">Response<textarea required name="body_text" defaultValue={draft.body_text} rows={10} className={inputClass}/></label>{draft.last_error&&<p className="mt-3 text-sm text-red-300">Previous attempt: {draft.last_error.replaceAll("_"," ")}</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><button disabled={draft.status==="sending"} className={`${buttonClass} disabled:opacity-40`}>Approve and send</button><p className="text-xs text-slate-500">Nothing sends until this button is pressed. Your edits become the final recorded response.</p></div>{timeline.length>0&&<details className="mt-4 text-xs text-slate-400"><summary className="cursor-pointer">Draft and approval history ({timeline.length})</summary><div className="mt-2 space-y-1">{timeline.reverse().map(item=><p key={item.id}>{item.revision_type.replaceAll("_"," ")} · {item.actor} · {formatDate(item.created_at)}</p>)}</div></details>}</form>})}{!openDrafts.length&&<Empty>No response is awaiting approval.</Empty>}</div></Card>
    <p className="text-xs text-slate-500">Safety rules: capacity is never described as confirmed without a live hold; deposit drafts use an existing private proposal-payment link when available; all recipient email still obeys controlled activation, suppression, daily limits, deliverability pause, and human approval.</p>
  </div>;
}
function Summary({label,value}){return <div className="rounded-lg bg-black/10 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>}
