import {getSupabaseAdmin} from "@/lib/server/supabase-admin";
import {Card,Empty,buttonClass,formatDate} from "../../office-ui";
import {resumeOutboundAfterDeliverabilityReview} from "../../actions";

function addressDomain(value){const match=String(value||"").match(/@([^>\s]+)/);return match?.[1]?.toLowerCase()||null;}
function percent(value){return `${(value*100).toFixed(value<0.01?2:1)}%`;}
const typeNames={inbound_confirmation:"Lead confirmations",internal_notification:"Internal notifications",prospecting:"Prospecting",proposal:"Proposals",nurture:"Nurture",booking:"Booking",client_lifecycle:"Client lifecycle",manual:"Manual"};

export default async function DeliverabilityPage({searchParams}){
  const params=await searchParams;
  // Live rolling windows are intentionally evaluated on each private page request.
  // eslint-disable-next-line react-hooks/purity
  const now=Date.now(),since30=new Date(now-30*86400000).toISOString(),since7=new Date(now-7*86400000).toISOString(),today=new Date(now).toISOString().slice(0,10),db=getSupabaseAdmin();
  const [configResult,messagesResult,inboundResult,countersResult,suppressionsResult,failuresResult,webhookResult]=await Promise.all([
    db.from("system_config").select("master_enabled,prospecting_enabled,outbound_auto_paused,prospecting_from_email,daily_prospecting_cap,proposal_email_enabled,daily_proposal_cap,daily_inbound_cap,daily_nurture_cap").eq("id",true).single(),
    db.from("messages").select("id,prospect_id,message_type,status,from_address,provider,provider_message_id,sent_at,created_at").eq("direction","outbound").gte("created_at",since30).order("created_at",{ascending:false}).limit(2000),
    db.from("messages").select("id,prospect_id,received_at,created_at").eq("direction","inbound").gte("created_at",since30).limit(2000),
    db.from("email_send_counters").select("message_type,reserved_count,sent_count,failed_count").eq("send_date",today),
    db.from("suppression_list").select("id,email,reason,source,created_at").gte("created_at",since30).order("created_at",{ascending:false}).limit(100),
    db.from("agent_log").select("id,agent_name,action,outcome,error,decision,created_at").in("outcome",["failed","blocked","escalated"]).gte("created_at",since30).order("created_at",{ascending:false}).limit(100),
    db.from("resend_webhook_events").select("event_type,processed_at").order("processed_at",{ascending:false}).limit(1).maybeSingle()
  ]);
  const config=configResult.data||{prospecting_from_email:null,daily_prospecting_cap:0,daily_proposal_cap:0,daily_inbound_cap:0,daily_nurture_cap:0,outbound_auto_paused:false},messages=messagesResult.data||[],inbound=inboundResult.data||[],counters=countersResult.data||[],suppressions=suppressionsResult.data||[],failures=(failuresResult.data||[]).filter(x=>/send|email|resend|outbound|proposal|nurture/i.test(`${x.agent_name} ${x.action}`)),lastWebhook=webhookResult.data;
  const typeMetrics=Object.entries(messages.reduce((all,m)=>{const key=m.message_type||"unknown",row=all[key]||{sent:0,delivered:0,failed:0,bounced:0,complained:0,replies:new Set(),prospects:new Set()};if(["sent","delivered","bounced","complained"].includes(m.status))row.sent++;if(m.status==="delivered")row.delivered++;if(m.status==="failed")row.failed++;if(m.status==="bounced")row.bounced++;if(m.status==="complained")row.complained++;if(m.prospect_id)row.prospects.add(m.prospect_id);all[key]=row;return all;},{})).map(([key,row])=>{for(const prospect of row.prospects)if(inbound.some(m=>m.prospect_id===prospect))row.replies.add(prospect);return {key,...row,replyRate:row.prospects.size?row.replies.size/row.prospects.size:0};});
  const prospecting7=messages.filter(m=>m.message_type==="prospecting"&&m.created_at>=since7&&["sent","delivered","bounced","complained"].includes(m.status)),bounces=prospecting7.filter(m=>m.status==="bounced").length,complaints=prospecting7.filter(m=>m.status==="complained").length,bounceRate=prospecting7.length?bounces/prospecting7.length:0,complaintRate=prospecting7.length?complaints/prospecting7.length:0;
  const transactionalFrom=process.env.RESEND_FROM_EMAIL||"",transactionalDomain=addressDomain(transactionalFrom),prospectingDomain=addressDomain(config.prospecting_from_email);
  let domains=[],domainError=null;try{if(!process.env.RESEND_API_KEY)throw new Error("Resend API key unavailable");const response=await fetch("https://api.resend.com/domains",{headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`},cache:"no-store"});if(!response.ok)throw new Error(`Resend returned ${response.status}`);const payload=await response.json();domains=payload.data||[];}catch(error){domainError=error instanceof Error?error.message:"Domain check failed";}
  const domainStatus=name=>domains.find(x=>x.name===name)?.status||"not found",transactionalStatus=transactionalDomain?domainStatus(transactionalDomain):"not configured",prospectingStatus=prospectingDomain?domainStatus(prospectingDomain):"not configured";
  const sentTotal=messages.filter(m=>["sent","delivered","bounced","complained"].includes(m.status)).length,delivered=messages.filter(m=>m.status==="delivered").length,failed=messages.filter(m=>m.status==="failed").length;
  const capFor={prospecting:config.daily_prospecting_cap,proposal:config.daily_proposal_cap,inbound_confirmation:config.daily_inbound_cap,nurture:config.daily_nurture_cap};
  const resumeReady=transactionalStatus==="verified"&&prospectingStatus==="verified"&&bounceRate<0.05&&complaintRate<0.001;
  const errorMessages={resume_checklist_required:"Complete every resume confirmation first.",threshold_still_exceeded:"Sending remains paused because a safety threshold is still exceeded.",resume_failed:"The automatic pause could not be cleared."};
  return <div className="space-y-8">
    {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?errorMessages[params.error]||"Deliverability action failed.":"Outbound automatic pause cleared after review."}</p>}
    <div><h2 className="text-3xl font-bold">Email deliverability</h2><p className="mt-2 text-slate-400">Sending health, reply performance, suppression activity, provider errors, verified domains, and safety controls.</p></div>
    {config.outbound_auto_paused&&<div className="rounded-2xl border border-red-400/30 bg-red-500/10 p-5 text-red-200"><p className="text-lg font-bold">Outbound is automatically paused</p><p className="mt-1 text-sm">The seven-day prospecting window crossed a bounce or complaint threshold. Recipient-facing prospecting remains blocked until the review below is completed.</p></div>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Card title="Sent · 30 days"><p className="text-3xl font-bold">{sentTotal}</p></Card><Card title="Delivered"><p className="text-3xl font-bold text-emerald-300">{delivered}</p></Card><Card title="Failed"><p className={`text-3xl font-bold ${failed?"text-red-300":"text-emerald-300"}`}>{failed}</p></Card><Card title="7-day bounce rate"><p className={`text-3xl font-bold ${bounceRate>=0.05?"text-red-300":"text-emerald-300"}`}>{percent(bounceRate)}</p></Card><Card title="Complaint rate"><p className={`text-3xl font-bold ${complaintRate>=0.001?"text-red-300":"text-emerald-300"}`}>{percent(complaintRate)}</p></Card></div>
    <Card title="Performance by message type"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-slate-400"><tr><th className="p-3">Type</th><th className="p-3">Sent</th><th className="p-3">Delivered</th><th className="p-3">Failed</th><th className="p-3">Bounced</th><th className="p-3">Complaints</th><th className="p-3">Reply rate</th></tr></thead><tbody>{typeMetrics.map(row=><tr key={row.key} className="border-t border-white/10"><td className="p-3 font-semibold">{typeNames[row.key]||row.key}</td><td className="p-3">{row.sent}</td><td className="p-3 text-emerald-300">{row.delivered}</td><td className="p-3 text-red-300">{row.failed}</td><td className="p-3 text-amber-300">{row.bounced}</td><td className="p-3 text-red-300">{row.complained}</td><td className="p-3">{percent(row.replyRate)}</td></tr>)}</tbody></table>{!typeMetrics.length&&<Empty>No outbound messages in the last 30 days.</Empty>}</div></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Sending identities"><div className="space-y-3">{[["Transactional",transactionalFrom,transactionalDomain,transactionalStatus],["Prospecting",config.prospecting_from_email,prospectingDomain,prospectingStatus]].map(([labelName,address,domain,status])=><div key={labelName} className="rounded-xl bg-white/5 p-4"><div className="flex justify-between gap-3"><strong>{labelName}</strong><span className={status==="verified"?"text-emerald-300":"text-amber-300"}>{status}</span></div><p className="mt-1 text-sm text-slate-300">{address||"Not configured"}</p><p className="text-xs text-slate-500">{domain||"No domain"}</p></div>)}{domainError&&<p className="text-sm text-red-300">Live Resend domain check unavailable: {domainError}</p>}</div></Card>
    <Card title="Today’s sending capacity"><div className="space-y-3">{Object.entries(capFor).map(([type,cap])=>{const counter=counters.find(x=>x.message_type===type)||{reserved_count:0,sent_count:0,failed_count:0};return <div key={type} className="rounded-lg bg-white/5 p-3 text-sm"><div className="flex justify-between"><strong>{typeNames[type]||type}</strong><span>{Math.max(0,(cap||0)-counter.reserved_count)} remaining</span></div><p className="mt-1 text-xs text-slate-500">{counter.sent_count} sent · {counter.reserved_count} reserved · {counter.failed_count} failed · cap {cap||0}</p></div>})}</div></Card></div>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Suppressions · 30 days" count={suppressions.length} tone={suppressions.length?"red":"green"}>{!suppressions.length?<Empty>No recent suppressions.</Empty>:<div className="max-h-96 space-y-2 overflow-auto">{suppressions.map(item=><div key={item.id} className="rounded-lg bg-white/5 p-3 text-sm"><div className="flex justify-between gap-3"><span>{item.email}</span><strong className="text-red-300">{item.reason.replaceAll("_"," ")}</strong></div><p className="mt-1 text-xs text-slate-500">{formatDate(item.created_at)} · {item.source||"unknown source"}</p></div>)}</div>}</Card>
    <Card title="Recent provider and automation errors" count={failures.length} tone={failures.length?"red":"green"}>{!failures.length?<Empty>No recent email-system failures.</Empty>:<div className="max-h-96 space-y-2 overflow-auto">{failures.map(item=><div key={item.id} className="rounded-lg bg-white/5 p-3 text-sm"><strong>{item.agent_name}: {item.action}</strong><p className="mt-1 text-red-300">{item.error||item.decision?.reason||item.outcome}</p><p className="mt-1 text-xs text-slate-500">{formatDate(item.created_at)}</p></div>)}</div>}</Card></div>
    <Card title="Safety thresholds"><div className="grid gap-3 sm:grid-cols-3"><p className="rounded-lg bg-white/5 p-3 text-sm"><strong className="block">Minimum sample</strong>10 prospecting sends</p><p className="rounded-lg bg-white/5 p-3 text-sm"><strong className="block">Bounce pause</strong>5.0% or higher</p><p className="rounded-lg bg-white/5 p-3 text-sm"><strong className="block">Complaint pause</strong>0.10% or higher</p></div><p className="mt-3 text-xs text-slate-500">Latest verified Resend webhook: {lastWebhook?`${lastWebhook.event_type} · ${formatDate(lastWebhook.processed_at)}`:"No webhook event recorded"}.</p></Card>
    {config.outbound_auto_paused&&<Card title="Safe resume checklist"><form action={resumeOutboundAfterDeliverabilityReview} className="space-y-3"><label className="flex gap-3 text-sm"><input type="checkbox" name="domains_confirmed" disabled={!resumeReady}/>Both sending domains are verified and current rates are below pause thresholds.</label><label className="flex gap-3 text-sm"><input type="checkbox" name="failures_reviewed"/>I reviewed recent provider failures and corrected the underlying issue.</label><label className="flex gap-3 text-sm"><input type="checkbox" name="suppressions_reviewed"/>I reviewed new suppressions and will not contact suppressed recipients.</label><button disabled={!resumeReady} className={`${buttonClass} disabled:opacity-40`}>Clear automatic pause</button></form></Card>}
    <p className="text-xs text-slate-500">Domain status is retrieved directly from Resend using a server-only API key. No credentials or raw webhook payloads are exposed in the browser.</p>
  </div>;
}
