import { getOfficeDb } from "@/lib/server/office-auth";
import {Card,Empty,ProspectLink,buttonClass,formatDate,formatMoney} from "../../office-ui";
import {refreshHolidaySlaEscalations,resolveHolidayEscalation} from "../../actions";

const holidaySources=["holiday_party_money_page","year_end_celebration_page","large_holiday_event_page"];

export default async function HolidaySlaPage(){
  // This force-dynamic server page measures response age at request time.
  // eslint-disable-next-line react-hooks/purity
  const now=Date.now(),since=new Date(now-30*86400000).toISOString(),db=(await getOfficeDb()).db;
  const [leadsResult,tasksResult,escalationsResult,runResult]=await Promise.all([
    db.from("leads").select("id,prospect_id,name,email,company,team_size,preferred_event_date,alternate_event_date,event_timezone,decision_timeline,created_at,context").in("lead_source",holidaySources).gte("created_at",since).order("created_at",{ascending:false}),
    db.from("tasks").select("id,prospect_id,title,priority,due_at,status").eq("source","holiday_sla").in("status",["open","in_progress"]).order("due_at").limit(100),
    db.from("tasks").select("id,prospect_id,title,description,priority,due_at,status,created_at").eq("source","holiday_sla_escalation").in("status",["open","in_progress"]).order("priority").order("created_at").limit(100),
    db.from("holiday_sla_escalation_runs").select("*").order("ran_at",{ascending:false}).limit(1).maybeSingle()
  ]);
  const leads=(leadsResult.data||[]).filter(x=>x.context?.synthetic_test!==true),tasks=tasksResult.data||[],escalations=escalationsResult.data||[],lastRun=runResult.data,prospectIds=[...new Set(leads.map(x=>x.prospect_id).filter(Boolean))],leadIds=leads.map(x=>x.id);
  const [messagesResult,paymentsResult]=await Promise.all([
    prospectIds.length?db.from("messages").select("id,prospect_id,sent_at,created_at,message_type").eq("direction","outbound").in("message_type",["manual","proposal"]).in("prospect_id",prospectIds).gte("created_at",since).order("created_at"):{data:[]},
    leadIds.length?db.from("stripe_events").select("id,lead_id,amount_total,currency,payment_status,paid_at").in("lead_id",leadIds).in("payment_status",["paid","complete"]):{data:[]}
  ]);
  const messages=messagesResult.data||[],payments=paymentsResult.data||[],firstResponse=new Map();
  for(const lead of leads){const created=new Date(lead.created_at).getTime(),reply=messages.find(m=>m.prospect_id===lead.prospect_id&&new Date(m.sent_at||m.created_at).getTime()>=created);if(reply)firstResponse.set(lead.id,new Date(reply.sent_at||reply.created_at).getTime());}
  const paidByLead=new Map(payments.map(p=>[p.lead_id,p]));
  const rows=leads.map(lead=>{const created=new Date(lead.created_at).getTime(),respondedAt=firstResponse.get(lead.id),minutes=Math.max(0,Math.round(((respondedAt||now)-created)/60000)),responded=Boolean(respondedAt),breached=minutes>30,isDecember=[lead.preferred_event_date,lead.alternate_event_date].some(x=>x&&new Date(`${x}T12:00:00Z`).getUTCMonth()===11);return {...lead,responded,respondedAt,minutes,breached,isDecember,payment:paidByLead.get(lead.id)};});
  const responded=rows.filter(x=>x.responded),withinTarget=responded.filter(x=>!x.breached).length,open=rows.filter(x=>!x.responded),breached=rows.filter(x=>x.breached),december=rows.filter(x=>x.isDecember),paid=rows.filter(x=>x.payment),dueTasks=tasks.filter(x=>x.due_at&&new Date(x.due_at).getTime()<=now);
  const compliance=responded.length?Math.round(withinTarget/responded.length*100):100;
  return <div className="space-y-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Holiday response SLA</h2><p className="mt-2 text-slate-400">Live response timing, active escalations, December capacity risk, deposits, and scheduled follow-ups.</p></div><form action={refreshHolidaySlaEscalations}><button className={buttonClass}>Run escalation check</button></form></div>
    <Card title="Active SLA escalations" count={escalations.length} tone={escalations.length?"red":"green"}><div className="space-y-3">{escalations.map(item=><div key={item.id} className={`rounded-xl border p-4 ${item.priority==="urgent"?"border-red-400/30 bg-red-500/10":"border-amber-400/30 bg-amber-500/10"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-300">{item.description}</p>{item.prospect_id&&<div className="mt-2"><ProspectLink id={item.prospect_id}/></div>}</div><form action={resolveHolidayEscalation}><input type="hidden" name="task_id" value={item.id}/><button className="rounded-lg border border-white/15 px-3 py-2 text-xs hover:bg-white/5">Mark resolved</button></form></div></div>)}{!escalations.length&&<Empty>No active holiday SLA escalations.</Empty>}</div>{lastRun&&<p className="mt-4 text-xs text-slate-500">Last automated check {formatDate(lastRun.ran_at)} · {lastRun.result?.resolved||0} resolved · {lastRun.result?.open_escalations||0} open</p>}</Card>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Card title="30-min compliance"><p className={`text-3xl font-bold ${compliance>=90?"text-emerald-300":"text-red-300"}`}>{compliance}%</p></Card><Card title="Awaiting response"><p className={`text-3xl font-bold ${open.length?"text-amber-300":"text-emerald-300"}`}>{open.length}</p></Card><Card title="SLA breaches"><p className={`text-3xl font-bold ${breached.length?"text-red-300":"text-emerald-300"}`}>{breached.length}</p></Card><Card title="December risks"><p className="text-3xl font-bold text-amber-300">{december.length}</p></Card><Card title="Deposits paid"><p className="text-3xl font-bold text-purple-300">{paid.length}</p></Card></div>
    <Card title="Needs attention now" count={open.filter(x=>x.minutes>=15).length+dueTasks.length} tone="red"><div className="space-y-3">{open.filter(x=>x.minutes>=15).map(lead=><div key={lead.id} className={`rounded-xl border p-4 ${lead.minutes>30?"border-red-400/30 bg-red-500/10":"border-amber-400/30 bg-amber-500/10"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div>{lead.prospect_id?<ProspectLink id={lead.prospect_id} name={lead.name} email={lead.email}/>:<p className="font-semibold">{lead.name||lead.email}</p>}<p className="mt-1 text-sm text-slate-300">{lead.company||"Company not provided"} · {lead.team_size||"Team size not provided"}</p></div><span className={lead.minutes>30?"text-red-300":"text-amber-300"}>{lead.minutes} min without response</span></div><p className="mt-2 text-xs text-slate-400">Requested {lead.preferred_event_date||"date missing"} · {lead.event_timezone||"time zone missing"}{lead.isDecember?" · December availability risk":""}</p></div>)}{!open.filter(x=>x.minutes>=15).length&&!dueTasks.length&&<Empty>No lead or scheduled follow-up currently needs attention.</Empty>}{dueTasks.slice(0,20).map(task=><div key={task.id} className="rounded-xl bg-white/5 p-4"><div className="flex flex-wrap justify-between gap-3"><p className="font-semibold">{task.title}</p><span className="text-sm text-red-300">Due {formatDate(task.due_at)}</span></div>{task.prospect_id&&<div className="mt-2"><ProspectLink id={task.prospect_id}/></div>}</div>)}</div></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Deposit-paid priority" count={paid.length} tone="gold">{!paid.length?<Empty>No holiday deposits in this window.</Empty>:<div className="space-y-3">{paid.map(lead=><div key={lead.id} className="rounded-xl bg-purple-500/10 p-4"><div className="flex justify-between gap-3">{lead.prospect_id?<ProspectLink id={lead.prospect_id} name={lead.name} email={lead.email}/>:<span>{lead.name}</span>}<strong>{formatMoney(lead.payment.amount_total/100,lead.payment.currency)}</strong></div><p className="mt-1 text-xs text-slate-400">Paid {formatDate(lead.payment.paid_at)} · event {lead.preferred_event_date||"date not confirmed"}</p></div>)}</div>}</Card>
    <Card title="December availability risk" count={december.length} tone="gold">{!december.length?<Empty>No December dates requested in this window.</Empty>:<div className="space-y-3">{december.map(lead=><div key={lead.id} className="rounded-xl bg-amber-500/10 p-4">{lead.prospect_id?<ProspectLink id={lead.prospect_id} name={lead.name} email={lead.email}/>:<p className="font-semibold">{lead.name}</p>}<p className="mt-1 text-sm">{lead.preferred_event_date||lead.alternate_event_date} · {lead.event_timezone||"time zone missing"}</p></div>)}</div>}</Card></div>
    <Card title="Recent response performance"><div className="space-y-2">{rows.slice(0,30).map(lead=><div key={lead.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-white/5 p-3 text-sm"><span>{lead.company||lead.name||lead.email}</span><span className={lead.breached?"text-red-300":lead.responded?"text-emerald-300":"text-amber-300"}>{lead.responded?`Responded in ${lead.minutes} min`:`Waiting ${lead.minutes} min`}</span></div>)}{!rows.length&&<Empty>No holiday leads in the last 30 days.</Empty>}</div></Card>
    <p className="text-xs text-slate-500">Response time uses the first recorded outbound CRM message after lead creation. Automated customer confirmations are not counted as a sales response.</p>
  </div>;
}
