import { getOfficeDb } from "@/lib/server/office-auth";
import {Card,Empty,ProspectLink,buttonClass,formatDate,inputClass} from "../../office-ui";
import {overrideLeadScore,refreshLeadScores} from "../../actions";

const holidaySources=["holiday_party_money_page","year_end_celebration_page","large_holiday_event_page"];
const componentNames={event_urgency:"Event urgency",team_size:"Team size",budget_package_fit:"Budget and package",decision_timeline:"Decision timing",large_event_complexity:"Event complexity",funnel_engagement:"Funnel engagement",deposit_activity:"Deposit activity"};
const band=score=>score>=70?"High priority":score>=40?"Medium priority":"Low priority";
const tone=score=>score>=70?"border-emerald-400/30 bg-emerald-500/10":score>=40?"border-amber-400/30 bg-amber-500/10":"border-white/10 bg-white/[0.03]";
const pct=value=>value===null||value===undefined?"—":`${(Number(value)*100).toFixed(1)}%`;

export default async function ScoringPage({searchParams}){
  const params=await searchParams,db=(await getOfficeDb()).db;
  const [{data:leads},{data:performance},{data:history}]=await Promise.all([
    db.from("leads").select("id,prospect_id,name,email,company,team_size,preferred_event_date,event_timezone,budget_range,package_interest,decision_timeline,lead_score,lead_score_reasons,lead_score_version,lead_score_override,lead_score_override_reason,lead_score_overridden_by,lead_score_overridden_at,lead_scored_at,created_at,context").in("lead_source",holidaySources).order("lead_score",{ascending:false}).limit(100),
    db.rpc("get_lead_score_performance",{p_days:180}),
    db.from("lead_score_history").select("id,lead_id,calculated_score,final_score,override_applied,scored_at").order("scored_at",{ascending:false}).limit(200),
  ]);
  const rows=(leads||[]).filter(x=>!x.context?.synthetic_test),bands=performance?.bands||[],high=rows.filter(x=>x.lead_score>=70),overrides=rows.filter(x=>x.lead_score_override!==null);
  return <div className="space-y-8">
    {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?"The scoring action could not be completed.":"Lead scores updated."}</p>}
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Lead scoring</h2><p className="mt-2 text-slate-400">Explainable event-priority scores that update with buyer urgency, fit, engagement, and payment activity.</p></div><form action={refreshLeadScores}><button className={buttonClass}>Recalculate all scores</button></form></div>
    <div className="grid gap-4 sm:grid-cols-4"><Card title="Scored holiday leads"><p className="text-3xl font-bold">{rows.length}</p></Card><Card title="High priority"><p className="text-3xl font-bold text-emerald-300">{high.length}</p></Card><Card title="Manual overrides"><p className="text-3xl font-bold text-purple-300">{overrides.length}</p></Card><Card title="Ranking evidence"><p className={`text-2xl font-bold ${performance?.useful?"text-emerald-300":"text-amber-300"}`}>{performance?.useful?"Validated":"Collecting data"}</p></Card></div>
    <Card title="Does priority predict conversion?"><div className="grid gap-3 sm:grid-cols-3">{["high","medium","low"].map(name=>{const item=bands.find(x=>x.band===name)||{};return <div key={name} className="rounded-xl bg-white/5 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{name}</p><p className="mt-2 text-2xl font-bold">{pct(item.conversion_rate)}</p><p className="mt-1 text-xs text-slate-500">{item.conversions||0} conversions from {item.leads||0} scored leads</p></div>})}</div><p className="mt-4 text-xs text-slate-500">The ranking is marked validated only when the high-priority band converts at least as well as the other observed bands. Until enough outcomes exist, the system reports “Collecting data.”</p></Card>
    <Card title="Prioritized holiday leads" count={rows.length}><div className="space-y-4">{rows.map(lead=>{const leadHistory=(history||[]).filter(x=>x.lead_id===lead.id);return <div key={lead.id} className={`rounded-2xl border p-5 ${tone(lead.lead_score||0)}`}><div className="flex flex-wrap items-start justify-between gap-4"><div>{lead.prospect_id?<ProspectLink id={lead.prospect_id} name={lead.name} email={lead.email}/>:<strong>{lead.name}</strong>}<p className="mt-1 text-sm text-slate-300">{lead.company||"Company missing"} · {lead.team_size||"size missing"} · {lead.preferred_event_date||"date missing"}</p><p className="mt-1 text-xs text-slate-500">{lead.budget_range||"budget missing"} · {lead.decision_timeline||"decision timing missing"} · scored {formatDate(lead.lead_scored_at)}</p></div><div className="text-right"><p className="text-3xl font-bold">{lead.lead_score??0}</p><p className="text-xs font-bold uppercase tracking-wide">{band(lead.lead_score||0)}</p>{lead.lead_score_override!==null&&<p className="mt-1 text-xs text-purple-200">Manual override</p>}</div></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{(lead.lead_score_reasons||[]).map(reason=><div key={reason.component} className="rounded-lg bg-black/10 p-3"><div className="flex justify-between gap-2 text-sm"><strong>{componentNames[reason.component]||reason.component}</strong><span className={reason.points>0?"text-emerald-300":"text-slate-500"}>+{reason.points}</span></div><p className="mt-1 text-xs text-slate-400">{reason.detail||"No signal"}</p></div>)}</div>
      {lead.lead_score_override!==null&&<div className="mt-4 rounded-lg bg-purple-500/10 p-3 text-sm"><strong>Override reason:</strong> {lead.lead_score_override_reason}<p className="mt-1 text-xs text-slate-400">{lead.lead_score_overridden_by} · {formatDate(lead.lead_score_overridden_at)}</p></div>}
      <div className="mt-4 grid gap-3 lg:grid-cols-[120px_1fr_auto_auto]"><form action={overrideLeadScore} className="contents"><input type="hidden" name="lead_id" value={lead.id}/><input type="hidden" name="mode" value="set"/><label className="text-xs">Override score<input required name="score" type="number" min="0" max="100" defaultValue={lead.lead_score_override??lead.lead_score??0} className={inputClass}/></label><label className="text-xs">Required reason<input required name="reason" defaultValue={lead.lead_score_override_reason||""} placeholder="Why should this lead move?" className={inputClass}/></label><button className={`${buttonClass} self-end`}>Save override</button></form>{lead.lead_score_override!==null&&<form action={overrideLeadScore} className="self-end"><input type="hidden" name="lead_id" value={lead.id}/><input type="hidden" name="mode" value="clear"/><button className="rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5">Use calculated score</button></form>}</div>
      {leadHistory.length>0&&<details className="mt-4 text-xs text-slate-400"><summary className="cursor-pointer">Score history ({leadHistory.length})</summary><div className="mt-2 flex flex-wrap gap-2">{leadHistory.slice(0,10).map(item=><span key={item.id} className="rounded bg-black/10 px-2 py-1">{item.calculated_score} calculated → {item.final_score} final · {formatDate(item.scored_at)}</span>)}</div></details>}
    </div>})}{!rows.length&&<Empty>No holiday leads have been scored yet.</Empty>}</div></Card>
    <p className="text-xs text-slate-500">Scores recalculate immediately when qualification fields, first-party engagement, or paid-deposit activity changes, and refresh nightly as requested dates approach. Manual overrides never erase the calculated score or its history.</p>
  </div>;
}
