import { getSupabaseAdmin } from "@/lib/server/supabase-admin";
import { validTimeZone, zonedWallTimeToUtc } from "@/lib/server/booking-time";
import { Card, Empty, ProspectLink, buttonClass, formatDate, inputClass } from "../../office-ui";
import { createEventCapacityHold, releaseEventCapacityHold, updateEventCapacityHost } from "../../actions";

const holidaySources = ["holiday_party_money_page", "year_end_celebration_page", "large_holiday_event_page"];
function normalizedTime(value) {
  const text=String(value||"").trim();
  const clock=text.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?$/i);
  if(!clock)return "14:00";
  let hour=Number(clock[1]); const minute=clock[2]; const meridiem=clock[3]?.toUpperCase();
  if(meridiem==="PM"&&hour<12)hour+=12; if(meridiem==="AM"&&hour===12)hour=0;
  return `${String(hour).padStart(2,"0")}:${minute}`;
}

export default async function CapacityPage({ searchParams }) {
  const params=await searchParams, db=getSupabaseAdmin(), now=new Date();
  await db.rpc("expire_event_capacity_holds");
  const [hostsResult,holdsResult,leadsResult,eventsResult]=await Promise.all([
    db.from("event_capacity_hosts").select("*").eq("active",true).order("created_at"),
    db.from("event_capacity_holds").select("*,leads(name,company,email),deals(title)").in("status",["tentative","confirmed"]).order("starts_at"),
    db.from("leads").select("id,prospect_id,name,email,company,team_size,preferred_event_date,alternate_event_date,event_timezone,preferred_time,decision_timeline,created_at").in("lead_source",holidaySources).not("preferred_event_date","is",null).gte("preferred_event_date",now.toISOString().slice(0,10)).order("preferred_event_date").limit(50),
    db.from("events").select("id,title,status,scheduled_start_time,attendee_count").not("scheduled_start_time","is",null).gte("scheduled_start_time",now.toISOString()).order("scheduled_start_time").limit(50),
  ]);
  const hosts=hostsResult.data||[], holds=holdsResult.data||[], leads=leadsResult.data||[], events=eventsResult.data||[];
  const availability=await Promise.all(leads.map(async lead=>{
    const timezone=validTimeZone(lead.event_timezone)?lead.event_timezone:(hosts[0]?.timezone||"America/New_York");
    const starts=zonedWallTimeToUtc(lead.preferred_event_date,normalizedTime(lead.preferred_time),timezone);
    const {data}=await db.rpc("check_event_capacity",{p_starts_at:starts.toISOString(),p_ends_at:new Date(starts.getTime()+60*60000).toISOString()});
    return [lead.id,data];
  }));
  const byLead=new Map(); availability.forEach(([id,value])=>byLead.set(id,value));
  return <div className="space-y-8">
    {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?`Capacity action stopped: ${String(params.error).replaceAll("_"," ")}.`:"Capacity updated."}</p>}
    <div><h2 className="text-3xl font-bold">Holiday capacity</h2><p className="mt-2 text-slate-400">Confirm a requested date before it appears in a proposal. Tentative holds expire automatically; scheduled events consume capacity.</p></div>
    <div className="grid gap-4 sm:grid-cols-4"><Card title="Active hosts"><p className="text-3xl font-bold">{hosts.length}</p></Card><Card title="Tentative holds"><p className="text-3xl font-bold text-amber-300">{holds.filter(x=>x.status==="tentative").length}</p></Card><Card title="Confirmed holds"><p className="text-3xl font-bold text-emerald-300">{holds.filter(x=>x.status==="confirmed").length}</p></Card><Card title="Upcoming events"><p className="text-3xl font-bold">{events.length}</p></Card></div>
    <Card title="Requested holiday dates" count={leads.length} tone={leads.some(x=>!byLead.get(x.id)?.available)?"gold":"green"}><div className="space-y-4">{leads.map(lead=>{const capacity=byLead.get(lead.id)||{},hasHold=holds.some(x=>x.lead_id===lead.id);return <div key={lead.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div>{lead.prospect_id?<ProspectLink id={lead.prospect_id} name={lead.name} email={lead.email}/>:<strong>{lead.name}</strong>}<p className="mt-1 text-sm text-slate-300">{lead.company||"Company not provided"} · {lead.team_size||"size missing"}</p><p className="mt-1 text-xs text-slate-400">{lead.preferred_event_date} · {lead.preferred_time||"time needs confirmation"} · {lead.event_timezone||"zone missing"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${hasHold?"bg-purple-500/15 text-purple-200":capacity.available?"bg-emerald-500/15 text-emerald-200":"bg-red-500/15 text-red-200"}`}>{hasHold?"HELD":capacity.available?capacity.december_prime_time_risk?"AVAILABLE · PRIME TIME":"AVAILABLE":String(capacity.reason||"CHECK NEEDED").replaceAll("_"," ").toUpperCase()}</span></div>{!hasHold&&<form action={createEventCapacityHold} className="mt-4 grid gap-3 sm:grid-cols-6"><input type="hidden" name="lead_id" value={lead.id}/><label className="text-xs">Date<input className={inputClass} name="date" type="date" required defaultValue={lead.preferred_event_date}/></label><label className="text-xs">Time<input className={inputClass} name="time" type="time" required defaultValue={normalizedTime(lead.preferred_time)}/></label><label className="text-xs">Time zone<input className={inputClass} name="timezone" required defaultValue={lead.event_timezone||hosts[0]?.timezone||"America/New_York"}/></label><label className="text-xs">Minutes<input className={inputClass} name="duration_minutes" type="number" min="30" max="240" defaultValue="60"/></label><label className="text-xs">Hold hours<input className={inputClass} name="hold_hours" type="number" min="1" max="168" defaultValue="48"/></label><button className={`${buttonClass} self-end`} disabled={!capacity.available}>Hold date</button></form>}</div>})}{!leads.length&&<Empty>No upcoming holiday date requests.</Empty>}</div></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Active date holds" count={holds.length}><div className="space-y-3">{holds.map(hold=><div key={hold.id} className="rounded-xl bg-white/5 p-4"><div className="flex flex-wrap justify-between gap-3"><strong>{hold.leads?.company||hold.leads?.name||hold.deals?.title||"Reserved event"}</strong><span className={hold.status==="confirmed"?"text-emerald-300":"text-amber-300"}>{hold.status}</span></div><p className="mt-1 text-sm">{formatDate(hold.starts_at)}–{new Intl.DateTimeFormat("en-US",{timeStyle:"short",timeZone:hosts.find(x=>x.id===hold.host_id)?.timezone||"America/New_York"}).format(new Date(hold.ends_at))}</p><p className="mt-1 text-xs text-slate-400">{hold.status==="tentative"?`Expires ${formatDate(hold.expires_at)}`:"Consumes capacity until the event is released."}</p><form action={releaseEventCapacityHold} className="mt-3"><input type="hidden" name="id" value={hold.id}/><button className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/5">Release</button></form></div>)}{!holds.length&&<Empty>No active capacity holds.</Empty>}</div></Card><Card title="Scheduled events"><div className="space-y-3">{events.map(event=><div key={event.id} className="rounded-xl bg-white/5 p-4"><div className="flex justify-between gap-3"><strong>{event.title||"Teamtastic event"}</strong><span className="text-xs text-slate-400">{String(event.status||"scheduled").replaceAll("_"," ")}</span></div><p className="mt-1 text-sm">{formatDate(event.scheduled_start_time)}{event.attendee_count?` · ${event.attendee_count} attendees`:""}</p></div>)}{!events.length&&<Empty>No future scheduled events.</Empty>}</div></Card></div>
    <Card title="Host settings"><div className="space-y-4">{hosts.map(host=><form key={host.id} action={updateEventCapacityHost} className="grid gap-3 rounded-xl bg-white/5 p-4 sm:grid-cols-4"><input type="hidden" name="id" value={host.id}/><div><strong>{host.name}</strong><p className="text-xs text-slate-400">Weekdays 9:00 AM–6:00 PM</p></div><label className="text-xs">Concurrent events<input className={inputClass} name="max_concurrent_events" type="number" min="1" max="20" defaultValue={host.max_concurrent_events}/></label><label className="text-xs">Host time zone<input className={inputClass} name="timezone" defaultValue={host.timezone}/></label><label className="text-xs">Blocked dates (comma separated)<input className={inputClass} name="blocked_dates" defaultValue={(host.blocked_dates||[]).join(", ")}/></label><button className={`${buttonClass} sm:col-span-4 sm:justify-self-start`}>Save host capacity</button></form>)}</div></Card>
    <p className="text-xs text-slate-500">Safety rule: holiday proposals with a requested date cannot be created until an active capacity hold exists. Holds expire every five minutes unless confirmed or released.</p>
  </div>;
}
