import { getOfficeDb } from "@/lib/server/office-auth";
import {Card,buttonClass,formatDate,inputClass} from "../../office-ui";
import {recordFinalCertificationAttestation,refreshFinalCertification,signOffFinalCertification} from "../../actions";

export default async function FinalCertificationPage({searchParams}){const params=await searchParams,db=(await getOfficeDb()).db;const [{data:run},{data:observations=[]}]=await Promise.all([db.from("final_production_certifications").select("*").order("started_at",{ascending:false}).limit(1).maybeSingle(),db.from("final_certification_observations").select("*").order("observed_at",{ascending:false}).limit(24)]);return <div className="space-y-8">
  <div><h2 className="text-3xl font-bold">Final production certification</h2><p className="mt-2 text-slate-400">Phase 11 combines verified preflight evidence with a real, monitored 24-hour production pilot. Final sign-off is database-gated.</p></div>
  {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-amber-500/10 text-amber-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?"A required certification gate is still incomplete.":"Certification evidence refreshed."}</p>}
  {!run?<Card title="Pilot not started"><p className="text-sm text-slate-400">The deployment must start the monitored pilot before evidence appears here.</p></Card>:<><div className="grid gap-4 sm:grid-cols-4"><Card title="Status"><p className="text-2xl font-bold text-purple-300">{run.status.replaceAll("_"," ")}</p></Card><Card title="Started"><p>{formatDate(run.started_at)}</p></Card><Card title="Observation ends"><p>{formatDate(run.observation_ends_at)}</p></Card><Card title="Observations"><p className="text-2xl font-bold">{observations.length}</p></Card></div>
  <Card title="Production pilot gates"><div className="space-y-3">{(run.latest_checks||[]).map(x=><div key={x.key} className={`rounded-lg border p-3 ${x.passed?"border-emerald-400/20 bg-emerald-500/10":"border-amber-400/20 bg-amber-500/10"}`}><p className="font-semibold">{x.passed?"Passed":"Pending"} · {x.key.replaceAll("_"," ")}</p><p className="text-sm text-slate-400">{x.detail}</p></div>)}</div></Card>
  <Card title="Preflight evidence"><div className="grid gap-2 sm:grid-cols-2">{Object.entries(run.preflight_evidence||{}).map(([key,value])=><p key={key} className="rounded-lg bg-white/5 p-3 text-sm"><span className={value===true?"text-emerald-300":"text-slate-300"}>{value===true?"Verified":"Recorded"}</span> · {key.replaceAll("_"," ")}</p>)}</div></Card>
  <Card title="Known limitations"><ul className="list-disc space-y-2 pl-5 text-sm text-slate-300">{(run.known_limitations||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></Card>
  <Card title="Record remaining manual evidence"><div className="grid gap-5 lg:grid-cols-2">{[["cross_browser_forms_verified","Safari and Firefox forms"],["email_auth_inbox_verified","Real inbox placement"]].map(([key,label])=><form action={recordFinalCertificationAttestation} key={key} className="rounded-lg bg-white/5 p-4"><input type="hidden" name="id" value={run.id}/><input type="hidden" name="evidence_key" value={key}/><p className="font-semibold">{label}</p><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="passed"/> I personally verified this gate passed</label><textarea required minLength={10} name="notes" rows={3} placeholder="Record browsers/inboxes tested, date, and result" className={inputClass}/><button className={buttonClass}>Record evidence</button></form>)}</div><p className="mt-3 text-xs text-slate-500">Each attestation is retained with the operator, timestamp, result, and notes.</p></Card>
  <div className="flex flex-wrap gap-3"><form action={refreshFinalCertification}><input type="hidden" name="id" value={run.id}/><button className={buttonClass}>Refresh pilot evidence</button></form>{run.status==="ready_for_signoff"&&<form action={signOffFinalCertification}><input type="hidden" name="id" value={run.id}/><button className={buttonClass}>Sign off launch readiness</button></form>}</div></>}
  <p className="text-xs text-slate-500">Outbound prospecting and automated follow-ups remain disabled during this certification pilot.</p>
  </div>}
