import Link from "next/link";
import { getOfficeDb } from "@/lib/server/office-auth";
import {Card,Empty,buttonClass,inputClass} from "../../office-ui";
import {saveCampaignAdSpend} from "../../actions";

const money=value=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value||0));
const pct=value=>value===null||value===undefined?"—":`${(Number(value)*100).toFixed(1)}%`;
const ratio=value=>value===null||value===undefined?"—":`${Number(value).toFixed(2)}×`;

export default async function RoiPage({searchParams}){
  const params=await searchParams,days=[7,30,90,365].includes(Number(params?.days))?Number(params.days):30,db=(await getOfficeDb()).db;
  const [{data:report,error},{data:spend}]=await Promise.all([db.rpc("get_lead_source_roi",{p_days:days}),db.from("campaign_ad_spend").select("*").order("spend_date",{ascending:false}).limit(50)]);
  const summary=report?.summary||{},campaigns=report?.campaigns||[],flagged=campaigns.filter(x=>x.traffic_without_qualified_leads);
  return <div className="space-y-8">
    {(params?.success||params?.error)&&<p className={`rounded-xl p-4 text-sm ${params.error?"bg-red-500/10 text-red-200":"bg-emerald-500/10 text-emerald-200"}`}>{params.error?"The advertising cost could not be saved.":"Advertising cost saved and ROI recalculated."}</p>}
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-bold">Lead-source ROI</h2><p className="mt-2 text-slate-400">Every campaign from first-party visit through qualified lead, discovery call, proposal, deposit, and revenue.</p></div><div className="flex gap-2">{[7,30,90,365].map(value=><Link key={value} href={`/office/roi?days=${value}`} className={`rounded-lg px-3 py-2 text-sm ${days===value?"bg-purple-600":"bg-white/5 hover:bg-white/10"}`}>{value===365?"1 year":`${value} days`}</Link>)}</div></div>
    {error?<Card title="Reporting unavailable" tone="red"><p className="text-red-300">Campaign reporting could not be calculated.</p></Card>:<>
    <div className="grid gap-4 sm:grid-cols-4 lg:grid-cols-8"><Metric title="Visitors" value={summary.visitors}/><Metric title="Leads" value={summary.leads}/><Metric title="Qualified" value={summary.qualified_leads}/><Metric title="Calls" value={summary.discovery_calls}/><Metric title="Proposals" value={summary.proposals_sent}/><Metric title="Deposits" value={summary.deposits}/><Metric title="Revenue" value={money(summary.revenue)}/><Metric title="ROAS" value={ratio(summary.roas)} tone="text-emerald-300"/></div>
    {flagged.length>0&&<Card title="Traffic without qualified leads" count={flagged.length} tone="gold"><div className="space-y-3">{flagged.map(row=><div key={`${row.source}-${row.medium}-${row.campaign}-${row.landing_page}`} className="rounded-xl bg-amber-500/10 p-4"><strong>{row.source} / {row.campaign}</strong><p className="mt-1 text-sm text-slate-300">{row.visitors} visitors reached {row.landing_page}, but none became qualified leads. Review targeting, campaign promise, and page-message alignment.</p></div>)}</div></Card>}
    <Card title={`Campaign performance · ${days} days`} count={campaigns.length}><div className="overflow-x-auto">{campaigns.length?<table className="w-full min-w-[1250px] text-left text-sm"><thead className="text-slate-400"><tr><th className="pb-3">Source / campaign</th><th>Page</th><th>Visitors</th><th>Leads</th><th>Qualified</th><th>Calls</th><th>Proposals</th><th>Deposits</th><th>Revenue</th><th>Spend</th><th>CPL</th><th>ROAS</th></tr></thead><tbody>{campaigns.map((row,index)=><tr key={`${row.source}-${row.campaign}-${row.landing_page}-${index}`} className="border-t border-white/10"><td className="py-3 pr-4"><strong>{row.source}</strong><span className="block text-xs text-slate-500">{row.medium} / {row.campaign}</span></td><td className="max-w-[220px] truncate pr-4">{row.landing_page}</td><td>{row.visitors}</td><td>{row.leads}<span className="block text-xs text-slate-500">{pct(row.visitor_to_lead_rate)}</span></td><td>{row.qualified_leads}<span className="block text-xs text-slate-500">{pct(row.qualification_rate)}</span></td><td>{row.discovery_calls}</td><td>{row.proposals_sent}</td><td>{row.deposits}</td><td>{money(row.revenue)}</td><td>{money(Number(row.spend_cents)/100)}</td><td>{row.cost_per_lead===null?"—":money(row.cost_per_lead)}</td><td className={Number(row.roas)>=1?"text-emerald-300":""}>{ratio(row.roas)}</td></tr>)}</tbody></table>:<Empty>No campaign activity in this reporting window.</Empty>}</div></Card></>}
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Record advertising cost"><form action={saveCampaignAdSpend} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Date<input required type="date" name="spend_date" defaultValue={new Date().toISOString().slice(0,10)} className={inputClass}/></label><label className="text-sm">Amount (USD)<input required type="number" min="0" step="0.01" name="amount" className={inputClass}/></label><label className="text-sm">Source<input required name="utm_source" placeholder="linkedin, google, meta" className={inputClass}/></label><label className="text-sm">Medium<input name="utm_medium" defaultValue="paid" className={inputClass}/></label><label className="text-sm">Campaign<input name="utm_campaign" defaultValue="unattributed" className={inputClass}/></label><label className="text-sm">Landing page<input name="landing_page" defaultValue="all" className={inputClass}/></label><label className="text-sm sm:col-span-2">Notes<input name="notes" placeholder="Optional invoice or campaign note" className={inputClass}/></label><button className={`${buttonClass} sm:col-span-2 sm:justify-self-start`}>Save cost and recalculate</button></form><p className="mt-3 text-xs text-slate-500">Saving the same date and campaign updates that day’s amount instead of duplicating it.</p></Card><Card title="Recent cost records" count={(spend||[]).length}><div className="max-h-[30rem] space-y-2 overflow-auto">{(spend||[]).map(item=><div key={item.id} className="rounded-lg bg-white/5 p-3 text-sm"><div className="flex justify-between gap-3"><strong>{item.utm_source} / {item.utm_campaign}</strong><span>{money(item.spend_cents/100)}</span></div><p className="mt-1 text-xs text-slate-500">{item.spend_date} · {item.utm_medium} · {item.landing_page}{item.notes?` · ${item.notes}`:""}</p></div>)}{!spend?.length&&<Empty>No advertising costs recorded yet.</Empty>}</div></Card></div>
    <p className="text-xs text-slate-500">Attribution uses first-party UTM and submission identifiers. Source aliases such as Facebook/Instagram, Google Ads/AdWords, and LinkedIn variants are normalized automatically. Revenue comes from reconciled deal payments.</p>
  </div>;
}
function Metric({title,value,tone=""}){return <Card title={title}><p className={`text-2xl font-bold ${tone}`}>{value??0}</p></Card>}
